/**
 * MOEI Knowledge Base
 * Comprehensive articles about UAE Ministry of Energy & Infrastructure services
 * Bilingual: English & Arabic
 */

export interface KnowledgeArticle {
  id: string
  titleEn: string
  titleAr: string
  contentEn: string
  contentAr: string
  category: string
  tags: string
}

export const moeiKnowledgeBase: KnowledgeArticle[] = [
  // ============================================================
  // ELECTRICITY & WATER (8 articles)
  // ============================================================
  {
    id: "kb-elect-001",
    titleEn: "Electricity Connection Application",
    titleAr: "طلب توصيل الكهرباء",
    contentEn: "To apply for a new electricity connection through MOEI, customers must submit an application via the MOEI portal at www.moei.gov.ae or visit one of our service centers. Required documents include a valid UAE PASS, property ownership deed or tenancy contract, Emirates ID, and a completed connection application form. The standard processing time for residential connections is 3-5 working days, while commercial connections may take 7-10 working days depending on the load requirements.\n\nConnection fees vary based on the property type and load capacity. Residential connections up to 60kW are subject to a standard fee of AED 1,500, while commercial and industrial connections are assessed individually. Emergency connections for critical infrastructure can be expedited through the urgent processing channel by contacting 8005555. All new connections require a site inspection by MOEI engineers before activation.\n\nCustomers can track their application status online using their UAE PASS credentials or by referencing their application number. For assistance with the connection process, contact our customer service team at 8005555 or visit any MOEI office during working hours (Sunday to Thursday, 7:30 AM to 2:30 PM).",
    contentAr: "للتقديم على توصيل كهرباء جديد من خلال وزارة الطاقة والبنية التحتية، يجب على العملاء تقديم الطلب عبر بوابة الوزارة على www.moei.gov.ae أو زيارة أحد مراكز الخدمة. المستندات المطلوبة تشمل الهوية الرقمية ( UAE PASS)، صك ملكية العقار أو عقد الإيجار، الهوية الإماراتية، ونموذج طلب التوصيل المكتمل. مدة المعالجة القياسية للتوصيلات السكنية هي 3-5 أيام عمل، بينما قد تستغرق التوصيلات التجارية 7-10 أيام عمل حسب متطلبات الحمل.\n\nتختلف رسوم التوصيل بناءً على نوع العقار وسعة الحمل. التوصيلات السكنية حتى 60 كيلو واط تخضع لرسوم قياسية قدرها 1,500 درهم، بينما يتم تقييم التوصيلات التجارية والصناعية بشكل فردي. يمكن تسريع التوصيلات الطارئة للبنية التحتية الحيوية عبر قناة المعالجة العاجلة بالاتصال على 8005555. تتطلب جميع التوصيلات الجديدة معاينة الموقع من قبل مهندسي الوزارة قبل التفعيل.\n\nيمكن للعملاء متابعة حالة طلبهم عبر الإنترنت باستخدام بيانات UAE PASS أو بالرجوع إلى رقم الطلب. للحصول على المساعدة في عملية التوصيل، تواصل مع فريق خدمة العملاء على 8005555 أو قم بزيارة أي مكتب للوزارة خلال ساعات العمل (الأحد إلى الخميس، 7:30 صباحاً إلى 2:30 مساءً).",
    category: "Electricity & Water",
    tags: "electricity, connection, application, new connection, power"
  },
  {
    id: "kb-elect-002",
    titleEn: "Water Connection Application",
    titleAr: "طلب توصيل المياه",
    contentEn: "MOEI manages water connection services for residential, commercial, and industrial properties across the UAE. To apply for a new water connection, customers need a valid UAE PASS, property documents, and the completed application form available on www.moei.gov.ae. The typical processing time is 2-5 working days for residential properties. Water connection fees start at AED 1,000 for standard residential units.\n\nWater quality testing is conducted as part of the connection process to ensure compliance with UAE water quality standards (GSO 149, GSO 150). MOEI operates and maintains water treatment facilities that deliver potable water meeting international safety standards. Customers can request water quality reports for their area through the online portal or by calling 8005555.\n\nFor water emergencies including burst pipes, contamination concerns, or supply disruptions, call the water emergency hotline at 998 immediately. This 24/7 emergency line is dedicated to water-related urgent issues. Non-urgent water supply inquiries can be directed to the main customer service line at 8005555.",
    contentAr: "تدير وزارة الطاقة والبنية التحتية خدمات توصيل المياه للمنشآت السكنية والتجارية والصناعية في جميع أنحاء الإمارات. للتقديم على توصيل مياه جديد، يحتاج العملاء إلى UAE PASS ساري، مستندات العقار، ونموذج الطلب المكتمل المتاح على www.moei.gov.ae. مدة المعالجة النموذجية هي 2-5 أيام عمل للمنشآت السكنية. تبدأ رسوم توصيل المياه من 1,000 درهم للوحدات السكنية القياسية.\n\nيتم إجراء اختبار جودة المياه كجزء من عملية التوصيل لضمان الامتثال لمعايير جودة المياه الإماراتية (GSO 149، GSO 150). تشغل الوزارة وتصون محطات معالجة المياه التي توفر مياه شرب تلبي معايير السلامة الدولية. يمكن للعملاء طلب تقارير جودة المياه لمنطقتهم عبر البوابة الإلكترونية أو بالاتصال على 8005555.\n\n لحالات الطوارئ المتعلقة بالمياه بما في ذلك انفجار الأنابيب أو مخاطر التلوث أو انقطاع الإمدادات، اتصل بخط الطوارئ على 998 فوراً. هذا الخط متاح على مدار الساعة للحالات العاجلة المتعلقة بالمياه. يمكن توجيه الاستفسارات غير العاجلة حول إمدادات المياه إلى خط خدمة العملاء الرئيسي على 8005555.",
    category: "Electricity & Water",
    tags: "water, connection, application, supply, quality"
  },
  {
    id: "kb-elect-003",
    titleEn: "Electricity & Water Billing",
    titleAr: "فواتير الكهرباء والمياه",
    contentEn: "MOEI issues electricity and water bills on a monthly basis. Bills are calculated based on meter readings, which can be submitted by customers through the MOEI portal or are read automatically by smart meters where available. The tariff structure follows a slab system — consumption within the first tier is charged at a lower rate, with progressively higher rates for higher consumption tiers. This tiered system encourages energy and water conservation.\n\nCustomers can pay bills through multiple channels: online via the MOEI website (www.moei.gov.ae), mobile app, bank transfer, or at any MOEI service center. A 10% late payment surcharge is applied to bills not paid within 30 days of the due date. For customers facing financial hardship, MOEI offers installment payment plans — we can help you arrange payment options.\n\nBill disputes can be raised through the online portal or by visiting a service center. Customers should retain their meter reading records and previous bills for reference. Disputed bills are typically resolved within 15 working days. Estimated bills are issued when meter readings are unavailable, and adjustments are made once actual readings are obtained.",
    contentAr: "تصدر وزارة الطاقة والبنية التحتية فواتير الكهرباء والمياه على أساس شهري. يتم حساب الفواتير بناءً على قراءات العداد، والتي يمكن للعملاء تقديمها عبر بوابة الوزارة أو تُقرأ تلقائياً بواسطة العدادات الذكية حيثما تتوفر. يتبع هيكل التعرفة نظام الشرائح — يُحسب الاستهلاك ضمن الشريحة الأولى بسعر أقل، مع أسعار تصاعدية أعلى لشرائح الاستهلاك الأعلى. يشجع هذا النظام المتدرج على ترشيد استهلاك الطاقة والمياه.\n\nيمكن للعملاء دفع الفواتير عبر قنوات متعددة: عبر الإنترنت من خلال موقع الوزارة (www.moei.gov.ae)، التطبيق المحمول، التحويل المصرفي، أو في أي مركز خدمة للوزارة. يُطبق غرامة تأخير بنسبة 10% على الفواتير غير المدفوعة خلال 30 يوماً من تاريخ الاستحقاق. للعملاء الذين يواجهون صعوبات مالية، تقدم الوزارة خطط دفع بالأقساط — يمكننا مساعدتك في ترتيب خيارات الدفع.\n\nيمكن الاعتراض على الفواتير عبر البوابة الإلكترونية أو بزيارة مركز خدمة. يجب على العملاء الاحتفاظ بسجلات قراءات العداد والفواتير السابقة كمرجع. يتم حل نزاعات الفواتير عادةً خلال 15 يوم عمل. تصدر فواتير تقديرية عندما لا تتوفر قراءات العداد، ويتم التعديل بمجرد الحصول على القراءات الفعلية.",
    category: "Electricity & Water",
    tags: "billing, electricity, water, payment, tariff, meter reading"
  },
  {
    id: "kb-elect-004",
    titleEn: "Electricity Emergency Reporting (997)",
    titleAr: "الإبلاغ عن طوارئ الكهرباء (997)",
    contentEn: "The electricity emergency hotline 997 is a dedicated 24/7 number for reporting electrical emergencies across the UAE. This includes power outages, downed power lines, electrical fires, exposed wiring, transformer failures, and any situation posing immediate electrical danger. When calling 997, provide your exact location, the nature of the emergency, and whether anyone is in immediate danger.\n\nMOEI emergency response teams are dispatched within 30 minutes for critical emergencies and within 2 hours for non-critical issues. For downed power lines, maintain a safe distance of at least 10 meters and keep others away until the emergency team arrives. Never attempt to touch or move downed power lines under any circumstances.\n\nFor non-emergency electricity issues such as flickering lights, minor voltage fluctuations, or general service inquiries, please call the main customer service line at 8005555 during working hours (Sun-Thu, 7:30-14:30). You can also report non-urgent issues through the MOEI website or mobile app, which are monitored during business hours.",
    contentAr: "خط طوارئ الكهرباء 997 هو رقم مخصص على مدار الساعة للإبلاغ عن حالات الطوارئ الكهربائية في جميع أنحاء الإمارات. يشمل ذلك انقطاعات الكهرباء، الأسلاك المتساقطة، حرائق كهربائية، أسلاك مكشوفة، أعطال المحولات، وأي حالة تشكل خطراً كهربائياً فورياً. عند الاتصال بـ 997، قدم موقعك الدقيق، وطبيعة الطوارئ، وما إذا كان هناك شخص في خطر مباشر.\n\nيتم إرسال فرق الاستجابة الطارئة للوزارة خلال 30 دقيقة لحالات الطوارئ الحرجة وخلال ساعتين للمشاكل غير الحرجة. بالنسبة للأسلاك المتساقطة، حافظ على مسافة آمنة لا تقل عن 10 أمتار وأبعد الآخرين حتى وصول فريق الطوارئ. لا تح أبداً لمس أو تحريك الأسلاك المتساقطة تحت أي ظرف.\n\nلقضايا الكهرباء غير الطارئة مثل الأضواء المتقطعة أو تقلبات الجهد الطفيفة أو الاستفسارات العامة، يرجى الاتصال بخط خدمة العملاء الرئيسي على 8005555 خلال ساعات العمل (الأحد-الخميس، 7:30-14:30). يمكنك أيضاً الإبلاغ عن المشاكل غير العاجلة عبر موقع الوزارة أو التطبيق المحمول، والتي يتم مراقبتها خلال ساعات العمل.",
    category: "Electricity & Water",
    tags: "emergency, electricity, 997, outage, power failure, safety"
  },
  {
    id: "kb-elect-005",
    titleEn: "Water Emergency Reporting (998)",
    titleAr: "الإبلاغ عن طوارئ المياه (998)",
    contentEn: "The water emergency hotline 998 operates 24/7 for reporting water-related emergencies throughout the UAE. This includes burst water mains, major leaks, water contamination, sewage backups, and complete loss of water supply. When calling 998, clearly state your location, describe the nature of the water emergency, and mention if there is any risk to public health or safety.\n\nMOEI water emergency teams aim to respond within 45 minutes for critical incidents such as major pipe bursts or contamination events. For localized supply issues, response times are typically within 4 hours. In cases of suspected water contamination, residents are advised to stop using tap water immediately and use bottled water until MOEI confirms the supply is safe. Boil-water advisories are issued when necessary through SMS alerts and the MOEI website.\n\nTo minimize water damage while waiting for the emergency team, turn off the main water valve if accessible. Document any damage with photographs for insurance purposes. After the emergency is resolved, MOEI provides a written incident report upon request, which can be used for insurance claims or compensation inquiries.",
    contentAr: "خط طوارئ المياه 998 يعمل على مدار الساعة للإبلاغ عن حالات الطوارئ المتعلقة بالمياه في جميع أنحاء الإمارات. يشمل ذلك انفجار خطوط المياه الرئيسية، التسريبات الكبرى، تلوث المياه، انسداد الصرف الصحي، وانقطاع إمدادات المياه بالكامل. عند الاتصال بـ 998، اذكر موقعك بوضوح، وصف طبيعة حالة الطوارئ، واذكر ما إذا كان هناك أي خطر على الصحة العامة أو السلامة.\n\nتهدف فرق طوارئ المياه بالوزارة إلى الاستجابة خلال 45 دقيقة للحالات الحرجة مثل انفجار الأنابيب الرئيسية أو حوادث التلوث. للمشاكل الم локلية في الإمداد، عادة ما تكون أوقات الاستجابة خلال 4 ساعات. في حالات الاشتباه في تلوث المياه، يُنصح السكان بالتوقف عن استخدام مياه الصنبور فوراً واستخدام المياه المعبأة حتى تؤكد الوزارة أن الإمداد آمن. يتم إصدار تحذيرات غلي المياه عند الضرورة عبر تنبيهات الرسائل القصيرة وموقع الوزارة.\n\nلتقليل أضرار المياه أثناء انتظار فريق الطوارئ، أغلق صمام المياه الرئيسي إذا كان متاحاً. وثق أي أضرار بالصور لأغراض التأمين. بعد حل الطوارئ، تقدم الوزارة تقرير حادث خطي عند الطلب، والذي يمكن استخدامه لمطالبات التأمين أو استفسارات التعويض.",
    category: "Electricity & Water",
    tags: "emergency, water, 998, burst pipe, contamination, supply"
  },
  {
    id: "kb-elect-006",
    titleEn: "Renewable Energy Programs",
    titleAr: "برامج الطاقة المتجددة",
    contentEn: "MOEI actively promotes renewable energy adoption across the UAE in alignment with the UAE Energy Strategy 2050, which targets 44% clean energy in the national energy mix by 2050. The ministry oversees solar energy programs, wind energy initiatives, and clean technology deployment. Residents and businesses can apply for permits to install rooftop solar panels through the MOEI portal.\n\nThe Shams Dubai initiative encourages building owners to install solar photovoltaic systems and connect them to the grid. Eligible installations can benefit from net metering, where excess electricity generated is fed back into the grid and credited against the customer's bill. MOEI provides technical guidelines and standards for solar installations to ensure safety and grid compatibility.\n\nFor large-scale renewable energy projects, MOEI offers licensing and regulatory guidance. The ministry also coordinates with the UAE Water and Electricity Authority and regional utilities to streamline interconnection processes. Educational resources about renewable energy options, cost savings, and environmental benefits are available on the MOEI website and at service centers.",
    contentAr: "تشجع وزارة الطاقة والبنية التحتية بنشاط تبني الطاقة المتجددة في الإمارات تتوافقاً مع استراتيجية الطاقة الإماراتية 2050، التي تستهدف 44% طاقة نظيفة في مزيج الطاقة الوطني بحلول 2050. تشرف الوزارة على برامج الطاقة الشمسية، مبادرات طاقة الرياح، ونشر التكنولوجيا النظيفة. يمكن للسكان والشركات التقدم للحصول على تصاريح لتركيب ألواح الطاقة الشمسية على الأسطح عبر بوابة الوزارة.\n\nمبادرة شمس دبي تشجع مالكي المباني على تركيب أنظمة الطاقة الكهروضوئية الشمسية وربطها بالشبكة. يمكن للتركيبات المؤهلة الاستفادة من القياس الصافي، حيث يتم تغذية الكهرباء الزائدة المولدة مرة أخرى إلى الشبكة وتُضاف كرصيد لفاتورة العميل. تقدم الوزارة إرشادات ومعايير فنية لتركيبات الطاقة الشمسية لضمان السلامة والتوافق مع الشبكة.\n\nلمشاريع الطاقة المتجددة الكبيرة، تقدم الوزارة إرشادات ترخيص وتنظيمية. كما تنسق الوزارة مع هيئة المياه والكهرباء الإماراتية والمرافق الإقليمية لتبسيط عمليات الربط بالشبكة. تتوفر موارد تعليمية حول خيارات الطاقة المتجددة وتوفير التكاليف والفوائد البيئية على موقع الوزارة وفي مراكز الخدمة.",
    category: "Electricity & Water",
    tags: "renewable energy, solar, wind, clean energy, shams dubai, net metering"
  },
  {
    id: "kb-elect-007",
    titleEn: "Energy Efficiency and Conservation",
    titleAr: "كفاءة الطاقة والترشيد",
    contentEn: "MOEI's energy efficiency programs aim to reduce per-capita energy consumption in the UAE, which ranks among the highest globally. The ministry provides guidelines for energy-efficient building design, appliance standards, and industrial energy management. The Emirates Energy Star program rates appliances and equipment for energy efficiency, helping consumers make informed purchasing decisions.\n\nBuilding owners and facility managers can access MOEI's energy audit services to identify consumption inefficiencies and receive recommendations for improvement. Common recommendations include upgrading to LED lighting, installing smart building management systems, improving HVAC efficiency, and implementing demand response strategies. MOEI offers incentives for buildings that achieve significant energy reductions.\n\nFor residential customers, simple conservation measures can reduce electricity bills by 20-30%. These include setting air conditioning to 24°C, using energy-efficient appliances, sealing air leaks, and utilizing natural lighting where possible. MOEI publishes seasonal energy-saving tips and runs awareness campaigns, especially during the peak summer months when cooling demand strains the electrical grid.",
    contentAr: "تهدف برامج كفاءة الطاقة في وزارة الطاقة والبنية التحتية إلى تقليل استهلاك الفرد من الطاقة في الإمارات، والذي يصنف من بين الأعلى عالمياً. تقدم الوزارة إرشادات لتصميم المباني الموفرة للطاقة ومعايير الأجهزة وإدارة الطاقة الصناعية. برنامج نجمة الطاقة الإماراتية يصنف الأجهزة والمعدات من حيث كفاءة الطاقة، مما يساعد المستهلكين على اتخاذ قرارات شراء مستنيرة.\n\nيمكن لأصحاب المباني ومديري المرافق الوصول إلى خدمات تدقيق الطاقة من الوزارة لتحديد أوجه القصور في الاستهلاك وتلقي توصيات التحسين. تشمل التوصيات الشائعة الترقية إلى إضاءة LED، تركيب أنظمة إدارة المباني الذكية، تحسين كفاءة التدفئة والتهوية وتكييف الهواء، وتطبيق استراتيجيات الاستجابة للطلب. تقدم الوزارة حوافز للمباني التي تحقق تخفيضات كبيرة في الطاقة.\n\nللعملاء السكنيين، يمكن لإجراءات الترشيد البسيطة تقليل فواتير الكهرباء بنسبة 20-30%. تشمل هذه ضبط التكييف على 24 درجة مئوية، استخدام الأجهزة الموفرة للطاقة، إغلاق تسربات الهواء، واستخدام الإضاءة الطبيعية حيثما أمكن. تنشر الوزارة نصائح توفير الطاقة الموسمية وتدير حملات توعية، خاصة خلال أشهر الصيف الذروة عندما يضع الطلب على التبريد ضغطاً على الشبكة الكهربائية.",
    category: "Electricity & Water",
    tags: "energy efficiency, conservation, audit, LED, HVAC, savings"
  },
  {
    id: "kb-elect-008",
    titleEn: "Smart Meter Installation and Readings",
    titleAr: "تركيب وقراءة العدادات الذكية",
    contentEn: "MOEI is deploying smart meters across the UAE to replace traditional electromechanical meters. Smart meters provide real-time electricity and water consumption data, enabling more accurate billing and helping customers monitor and manage their usage. The smart meter rollout is being conducted in phases, with priority given to new connections and high-consumption customers.\n\nCustomers with smart meters can view their real-time consumption data through the MOEI online portal and mobile app. This includes hourly, daily, and monthly usage graphs, consumption alerts when approaching tier thresholds, and comparison tools showing usage trends. Smart meters also enable remote disconnection and reconnection, reducing the need for field visits and speeding up service changes.\n\nIf you receive an estimated bill despite having a smart meter, please report it to 8005555. Smart meter data is encrypted and transmitted securely to protect customer privacy. Customers can opt for SMS or email notifications for consumption milestones and bill generation. The smart meter installation itself is free of charge for existing customers as part of the national rollout program.",
    contentAr: "تقوم وزارة الطاقة والبنية التحتية بنشر العدادات الذكية في جميع أنحاء الإمارات لتحل محل العدادات الكهروميكانيكية التقليدية. توفر العدادات الذكية بيانات استهلاك الكهرباء والمياه في الوقت الفعلي، مما يتيح فوترة أكثر دقة ويساعد العملاء على مراقبة وإدارة استهلاكهم. يتم نشر العدادات الذكية على مراحل، مع إعطاء الأولوية للتوصيلات الجديدة والعملاء ذوي الاستهلاك العالي.\n\nيمكن للعملاء الذين يمتلكون عدادات ذكية عرض بيانات استهلاكهم في الوقت الفعلي عبر البوابة الإلكترونية والتطبيق المحمول للوزارة. يشمل ذلك رسومات الاستهلاك بالساعة واليوم والشهر، تنبيهات الاستهلاك عند الاقتراب من حدود الشرائح، وأدوات مقارنة تظهر اتجاهات الاستخدام. كما تمكن العدادات الذكية الفصل وإعادة التوصيل عن بُعد، مما يقلل الحاجة للزيارات الميدانية ويسرع تغييرات الخدمة.\n\nإذا تلقيت فاتورة تقديرية رغم امتلاكك عداداً ذكياً، يرجى الإبلاغ عن ذلك على 8005555. يتم تشفير بيانات العدادات الذكية ونقلها بشكل آمن لحماية خصوصية العميل. يمكن للعملاء اختيار إشعارات الرسائل القصيرة أو البريد الإلكتروني لمعالم الاستهلاك وإصدار الفواتير. تركيب العداد الذكي نفسه مجاني للعملاء الحاليين كجزء من برنامج النشر الوطني.",
    category: "Electricity & Water",
    tags: "smart meter, reading, installation, monitoring, real-time"
  },

  // ============================================================
  // HOUSING (5 articles)
  // ============================================================
  {
    id: "kb-house-001",
    titleEn: "Sheikh Zayed Housing Program",
    titleAr: "برنامج الشيخ زايد للإسكان",
    contentEn: "The Sheikh Zayed Housing Program (SZHP), overseen by MOEI, provides housing support to UAE nationals. The program offers several types of assistance: government housing grants (free housing), housing loans with subsidized interest rates, maintenance and expansion loans, and land grants. Eligibility requires UAE citizenship, a valid UAE PASS, and meeting income thresholds which vary by program type.\n\nGovernment housing grants are provided to low-income UAE nationals who do not own residential property. The program constructs housing units across all emirates, with modern designs meeting UAE building codes. Housing loans of up to AED 800,000 are available with repayment periods of up to 25 years at reduced interest rates. Loan applicants must demonstrate the ability to make monthly repayments, typically through salary deduction arrangements.\n\nApplications are submitted through the SZHP portal or MOEI service centers. Processing times range from 30-90 days depending on the type of assistance. Priority is given to families with limited income, newly married couples, and residents of remote areas. The program has delivered over 40,000 housing units since its inception, reflecting the UAE leadership's commitment to ensuring dignified housing for all citizens.",
    contentAr: "برنامج الشيخ زايد للإسكان، الذي تشرف عليه وزارة الطاقة والبنية التحتية، يقدم الدعم السكني للمواطنين الإماراتيين. يقدم البرنامج عدة أنواع من المساعدة: منح إسكان حكومية (سكن مجاني)، قروض إسكانية بفوائد مدعومة، قروض صيانة وتوسعة، ومنح أراضي. يتطلب الأهلية الجنسية الإماراتية، UAE PASS ساري، وتلبية حدود الدخل التي تختلف حسب نوع البرنامج.\n\nتُقدم منح الإسكان الحكومية للمواطنين الإماراتيين ذوي الدخل المحدود الذين لا يملكون عقارات سكنية. يبني البرنامج وحدات سكنية في جميع الإمارات بتصاميم حديثة تلبي رموز البناء الإماراتية. تتوفر قروض إسكانية تصل إلى 800,000 درهم بفترات سداد تصل إلى 25 عاماً بأسعار فائدة مخفضة. يجب على متقدمي القروض إثبات القدرة على السداد الشهري، عادةً من خلال ترتيبات الخصم من الراتب.\n\nتُقدم الطلبات عبر بوابة البرنامج أو مراكز خدمة الوزارة. تتراوح أوقات المعالجة من 30-90 يوماً حسب نوع المساعدة. يُعطى الأولوية للأسر ذات الدخل المحدود، المتزوجين حديثاً، وسكان المناطق النائية. قدم البرنامج أكثر من 40,000 وحدة سكنية منذ تأسيسه، مما يعكس التزام قيادة الإمارات بضمان سكن كريم لجميع المواطنين.",
    category: "Housing",
    tags: "housing, sheikh zayed, loan, grant, citizens, housing program"
  },
  {
    id: "kb-house-002",
    titleEn: "Federal Housing Loans",
    titleAr: "القروض الإسكانية الاتحادية",
    contentEn: "MOEI administers federal housing loans for UAE nationals seeking to build, purchase, or renovate residential properties. Loan amounts range from AED 200,000 to AED 800,000 depending on the applicant's income, family size, and the purpose of the loan. Interest rates are subsidized by the government, typically ranging from 0% to 2%, significantly below market rates.\n\nTo qualify for a federal housing loan, applicants must be UAE nationals, at least 21 years old, not own more than one residential property, and have a monthly income between AED 5,000 and AED 35,000. Required documents include Emirates ID, salary certificate, bank statements for the last 6 months, property documents or land deed, and a valid UAE PASS.\n\nThe repayment period extends up to 25 years with flexible payment options including salary deduction and direct debit. Early repayment is allowed without penalties. Loan disbursement is made in stages: 30% at construction start, 30% at structural completion, 30% at finishing stage, and 10% upon handover. For property purchase loans, the full amount is disbursed upon completion of the sale transaction.",
    contentAr: "تدير وزارة الطاقة والبنية التحتية القروض الإسكانية الاتحادية للمواطنين الإماراتيين الراغبين في بناء أو شراء أو تجديد العقارات السكنية. تتراوح مبالغ القروض من 200,000 إلى 800,000 درهم حسب دخل مقدم الطلب وحجم أسرته والغرض من القرض. أسعار الفائدة مدعومة من الحكومة، وتتراوح عادةً من 0% إلى 2%، وهي أقل بكثير من الأسعار السوقية.\n\nللتأهل للقرض الإسكاني الاتحادي، يجب أن يكون المتقدم مواطناً إماراتياً، عمره 21 عاماً على الأقل، لا يملك أكثر من عقار سكني واحد، وله دخل شهري بين 5,000 و35,000 درهم. المستندات المطلوبة تشمل الهوية الإماراتية، شهادة الراتب، كشوف حسابات بنكية لآخر 6 أشهر، مستندات العقار أو صك الأرض، وUAE PASS ساري.\n\nتمتد فترة السداد حتى 25 عاماً مع خيارات دفع مرنة تشمل الخصم من الراتب والخصم المباشر. يُسمح بالسداد المبكر بدون غرامات. يتم صرف القرض على مراحل: 30% عند بدء البناء، 30% عند الانتهاء الهيكلي، 30% عند مرحلة التشطيب، و10% عند التسليم. لقروض شراء العقارات، يتم صرف المبلغ بالكامل عند إتمام معاملة البيع.",
    category: "Housing",
    tags: "housing, federal loan, renovation, purchase, citizens, repayment"
  },
  {
    id: "kb-house-003",
    titleEn: "Housing Maintenance and Renovation",
    titleAr: "صيانة وتجديد المساكن",
    contentEn: "MOEI provides maintenance and renovation support for UAE national homeowners through subsidized loans and direct maintenance programs. The Housing Maintenance Loan covers essential repairs such as plumbing, electrical systems, roofing, air conditioning, and structural repairs. Loan amounts for maintenance range from AED 50,000 to AED 200,000 with preferential interest rates and repayment periods of up to 10 years.\n\nThe Priority Maintenance Program targets homes that are over 15 years old and require critical structural or systems repairs. MOEI conducts periodic housing condition surveys and proactively identifies homes needing maintenance. Homeowners can also apply directly for maintenance assistance through the MOEI portal. Emergency maintenance requests for issues affecting habitability (e.g., roof leaks, electrical hazards) are processed within 48 hours.\n\nFor renovation and expansion projects, including adding rooms, upgrading kitchens and bathrooms, or improving energy efficiency, separate renovation loans are available. All renovation work must comply with UAE building codes and require MOEI approval before construction begins. Unauthorized modifications may result in penalties and requirement to restore the property to its approved condition.",
    contentAr: "تقدم وزارة الطاقة والبنية التحتية دعم الصيانة والتجديد لأصحاب المنازل من المواطنين الإماراتيين من خلال قروض مدعومة وبرامج صيانة مباشرة. يغطي قرض صيانة المساكن الإصلاحات الأساسية مثل السباكة والأنظمة الكهربائية والسقف وتكييف الهواء والإصلاحات الهيكلية. تتراوح مبالغ قروض الصيانة من 50,000 إلى 200,000 درهم بأسعار فائدة تفضيلية وفترات سداد تصل إلى 10 سنوات.\n\nيستهدف برنامج الصيانة ذو الأولوية المنازل التي تزيد أعمارها عن 15 عاماً وتتطلب إصلاحات هيكلية أو أنظمة حرجة. تجري الوزارة مسوحات دورية لحالة المساكن وتحدد استباقياً المنازل التي تحتاج صيانة. يمكن لأصحاب المنازل أيضاً التقديم مباشرة للحصول على مساعدة الصيانة عبر بوابة الوزارة. تتم معالجة طلبات الصيانة الطارئة للمشاكل التي تؤثر على الصلاحية للسكن (مثل تسرب السقف، المخاطر الكهربائية) خلال 48 ساعة.\n\nلمشاريع التجديد والتوسعة، بما في ذلك إضافة غرف أو ترقية المطابخ والحمامات أو تحسين كفاءة الطاقة، تتوفر قروض تجديد منفصلة. يجب أن يتوافق جميع عمل التجديد مع رموز البناء الإماراتية ويتطلب موافقة الوزارة قبل بدء البناء. قد تؤدي التعديلات غير المصرح بها إلى غرامات ومتطلبات استعادة العقار لحالته المعتمدة.",
    category: "Housing",
    tags: "housing, maintenance, renovation, repair, expansion, loan"
  },
  {
    id: "kb-house-004",
    titleEn: "Road and Construction Permits",
    titleAr: "تصاريح الطرق والبناء",
    contentEn: "MOEI issues permits for road works and construction activities that affect federal infrastructure. This includes permits for road excavations, utility crossings, temporary road closures, and construction near federal highways. All applications must be submitted through the MOEI online portal with detailed engineering plans and traffic management proposals where applicable.\n\nRoad excavation permits require the applicant to provide a detailed work plan, including the scope of excavation, timeline, safety measures, and road restoration specifications. The standard processing time is 10-15 working days. Fees vary based on the road classification (federal highway, arterial road, local road) and the duration of the work. Temporary road closure permits require additional review by the traffic safety committee and may take up to 30 working days.\n\nConstruction permits near federal infrastructure ensure that building activities do not compromise the integrity of roads, bridges, and utilities. Setback requirements must be observed, and structural impact assessments may be required for projects within 50 meters of federal highways. Violations of permit conditions result in stop-work orders and potential fines ranging from AED 10,000 to AED 500,000 depending on severity.",
    contentAr: "تصدر وزارة الطاقة والبنية التحتية تصاريح لأعمال الطرق وأنشطة البناء التي تؤثر على البنية التحتية الاتحادية. يشمل ذلك تصاريح حفر الطرق، العبور تحت المرافق، إغلاق الطرق المؤقت، والبناء بالقرب من الطرق السريعة الاتحادية. يجب تقديم جميع الطلبات عبر البوابة الإلكترونية للوزارة مع خطط هندسية مفصلة ومقترحات إدارة المرور حيثما ينطبق.\n\nتتطلب تصاريح حفر الطرق من مقدم الطلب تقديم خطة عمل مفصلة، تشمل نطاق الحفر والجدول الزمني وتدابير السلامة ومواصفات استعادة الطريق. مدة المعالجة القياسية هي 10-15 يوم عمل. تختلف الرسوم حسب تصنيف الطريق (طريق سريع اتحادي، طريق رئيسي، طريق محلي) ومدة العمل. تتطلب تصاريح إغلاق الطرق المؤقت مراجعة إضافية من لجنة سلامة المرور وقد تستغرق حتى 30 يوم عمل.\n\nتضمن تصاريح البناء بالقرب من البنية التحتية الاتحادية أن أنشطة البناء لا تعرض سلامة الطرق والجسور والمرافق للخطر. يجب مراعاة متطلبات المسافة المتبقية، وقد يلزم تقييم الأثر الهيكلي للمشاريع التي تقع ضمن 50 متراً من الطرق السريعة الاتحادية. يؤدي انتهاك شروط التصاريح إلى أوامر وقف العمل وغرامات محتملة تتراوح من 10,000 إلى 500,000 درهم حسب الخطورة.",
    category: "Housing",
    tags: "permit, road, construction, excavation, federal highway, building"
  },
  {
    id: "kb-house-005",
    titleEn: "Construction Permits for Federal Buildings",
    titleAr: "تصاريح البناء للمباني الاتحادية",
    contentEn: "MOEI regulates construction permits for federal buildings and infrastructure projects across the UAE. All federal construction projects must obtain approval from MOEI before commencing work. The permit process ensures compliance with the UAE Federal Building Code, safety standards, and environmental regulations. Applications are submitted via the MOEI portal with architectural drawings, structural calculations, MEP plans, and environmental impact assessments.\n\nThe review process involves multiple stages: initial document review (5-10 working days), technical review by MOEI engineers (15-20 working days), and final approval (5 working days). Projects exceeding AED 50 million in value require additional review by the Federal Infrastructure Committee. All federal buildings must achieve a minimum 2-pearl rating under the Estidama Pearl Rating System or equivalent green building certification.\n\nConstruction permits are valid for 12 months from the date of issue. Extensions can be requested if construction has not commenced within this period, subject to review and payment of extension fees. Regular inspections are conducted during construction to verify compliance with approved plans. Non-compliance can result in stop-work orders, fines, or permit revocation.",
    contentAr: "تنظم وزارة الطاقة والبنية التحتية تصاريح البناء للمباني الاتحادية ومشاريع البنية التحتية في جميع أنحاء الإمارات. يجب على جميع مشاريع البناء الاتحادية الحصول على موافقة الوزارة قبل بدء العمل. تضمن عملية التصريح الامتثال لرمز البناء الاتحادي الإماراتي ومعايير السلامة واللوائح البيئية. تُقدم الطلبات عبر بوابة الوزارة مع الرسومات المعمارية والحسابات الهيكلية وخطوط MEP وتقييمات الأثر البيئي.\n\nتشمل عملية المراجعة مراحل متعددة: مراجعة المستندات الأولية (5-10 أيام عمل)، مراجعة فنية من مهندسي الوزارة (15-20 يوم عمل)، والموافقة النهائية (5 أيام عمل). المشاريع التي تتجاوز قيمتها 50 مليون درهم تتطلب مراجعة إضافية من اللجنة الاتحادية للبنية التحتية. يجب على جميع المباني الاتحادية تحقيق تصنيف لؤلؤتين كحد أدنى ضمن نظام تصنيف استدامة أو شهادة بناء أخضر معادلة.\n\nتصاريح البناء صالحة لمدة 12 شهراً من تاريخ الإصدار. يمكن طلب تمديدات إذا لم يبدأ البناء خلال هذه الفترة، خاضعة للمراجعة ودفع رسوم التمديد. يتم إجراء عمليات تفتيش منتظمة أثناء البناء للتحقق من الامتثال للخطط المعتمدة. قد يؤدي عدم الامتثال إلى أوامر وقف العمل أو غرامات أو إلغاء التصريح.",
    category: "Housing",
    tags: "construction, permit, federal building, building code, estidama, safety"
  },

  // ============================================================
  // PETROLEUM & ENERGY (4 articles)
  // ============================================================
  {
    id: "kb-petrol-001",
    titleEn: "Petroleum Licensing and Regulation",
    titleAr: "ترخيص وتنظيم البترول",
    contentEn: "MOEI oversees the licensing and regulation of petroleum-related activities in the UAE, including exploration, production, refining, storage, and distribution. Companies seeking to operate in the petroleum sector must obtain the appropriate licenses from MOEI before commencing operations. The licensing process includes environmental impact assessment, safety plan review, and financial capability verification.\n\nLicense categories include: Exploration License (for geological surveys and exploratory drilling), Production License (for extracting and processing hydrocarbons), Storage and Distribution License (for fuel storage facilities and distribution networks), and Retail License (for fuel stations). Each category has specific requirements regarding technical qualifications, environmental compliance, and operational safety standards.\n\nLicense applications are submitted through the MOEI portal with supporting documentation including company registration, technical qualifications of key personnel, environmental management plans, and proof of financial capacity. Processing times vary from 30-90 days depending on the license category. Annual license renewals require demonstration of continued compliance with all regulatory requirements. Non-compliance can result in license suspension, fines up to AED 5 million, or permanent revocation.",
    contentAr: "تشرف وزارة الطاقة والبنية التحتية على ترخيص وتنظيم الأنشطة المتعلقة بالبترول في الإمارات، بما في ذلك الاستكشاف والإنتاج والتكرير والتخزين والتوزيع. يجب على الشركات الراغبة في العمل في قطاع البترول الحصول على التراخيص المناسبة من الوزارة قبل بدء العمليات. تشمل عملية الترخيص تقييم الأثر البيئي ومراجعة خطة السلامة والتحقق من القدرة المالية.\n\nتشمل فئات الترخيص: رخصة الاستكشاف (للمسوحات الجيولوجية والحفر الاستكشافي)، رخصة الإنتاج (لاستخراج ومعالجة الهيدروكربونات)، رخصة التخزين والتوزيع (لمنشآت تخزين الوقود وشبكات التوزيع)، ورخصة التجزئة (لمحطات الوقود). لكل فئة متطلبات محددة فيما يتعلق بالمؤهلات الفنية والامتثال البيئي ومعايير السلامة التشغيلية.\n\nتُقدم طلبات الترخيص عبر بوابة الوزارة مع المستندات الداعمة بما في ذلك تسجيل الشركة والمؤهلات الفنية للموظفين الرئيسيين وخطط الإدارة البيئية وإثبات القدرة المالية. تختلف أوقات المعالجة من 30-90 يوماً حسب فئة الترخيص. تتطلب التجديدات السنوية إثبات الاستمرار في الامتثال لجميع المتطلبات التنظيمية. قد يؤدي عدم الامتثال إلى تعليق الترخيص أو غرامات تصل إلى 5 ملايين درهم أو الإلغاء الدائم.",
    category: "Petroleum & Energy",
    tags: "petroleum, licensing, regulation, exploration, production, fuel"
  },
  {
    id: "kb-petrol-002",
    titleEn: "Fuel Station Complaints and Regulation",
    titleAr: "شكاوى محطات الوقود والتنظيم",
    contentEn: "MOEI regulates fuel stations across the UAE and handles consumer complaints related to fuel quality, pricing, service standards, and safety violations. If you experience issues at a fuel station — such as incorrect fuel pricing, contaminated fuel, malfunctioning pumps, or safety hazards — you can file a complaint through the MOEI portal, by calling 8005555, or by visiting a service center.\n\nWhen filing a fuel station complaint, provide the station name and location, date and time of the incident, pump number if applicable, and a detailed description of the issue. Photographic evidence strengthens your complaint. MOEI investigates all complaints within 10 working days and keeps complainants informed of progress. If the complaint is substantiated, corrective actions are mandated and may include fines, temporary closure, or license review.\n\nFuel prices in the UAE are regulated and updated monthly by the UAE Fuel Price Follow-up Committee. Current fuel prices are published on the MOEI website at the beginning of each month. Fuel stations are required to display prices clearly at every pump and on price boards. Any discrepancy between displayed prices and charged amounts should be reported immediately.",
    contentAr: "تنظم وزارة الطاقة والبنية التحتية محطات الوقود في جميع أنحاء الإمارات وتتولى شكاوى المستهلكين المتعلقة بجودة الوقود والأسعار ومعايير الخدمة وانتهاكات السلامة. إذا واجهت مشاكل في محطة وقود — مثل تسعير غير صحيح أو وقود ملوث أو مضخات معطلة أو مخاطر سلامة — يمكنك تقديم شكوى عبر بوابة الوزارة أو بالاتصال على 8005555 أو زيارة مركز خدمة.\n\nعند تقديم شكوى عن محطة وقود، قدم اسم المحطة وموقعها وتاريخ ووقت الحادث ورقم المضخة إن وجد ووصفاً تفصيلياً للمشكلة. الأدلة المصورة تقوي شكواك. تحقق الوزارة في جميع الشكاوى خلال 10 أيام عمل وتبقي مقدمي الشكاوى على اطلاع بالتقدم. إذا تم التأكد من الشكوى، يتم إلزام الإجراءات التصحيحية التي قد تشمل غرامات أو إغلاقاً مؤقتاً أو مراجعة الترخيص.\n\nأسعار الوقود في الإمارات منظمة ومحدثة شهرياً من قبل لجنة متابعة أسعار الوقود الإماراتية. يتم نشر أسعار الوقود الحالية على موقع الوزارة في بداية كل شهر. يجب على محطات الوقود عرض الأسعار بوضوح عند كل مضخة وعلى لوحات الأسعار. يجب الإبلاغ فوراً عن أي تناقض بين الأسعار المعروضة والمبالغ المحصلة.",
    category: "Petroleum & Energy",
    tags: "fuel station, complaint, pricing, quality, regulation, pump"
  },
  {
    id: "kb-petrol-003",
    titleEn: "Energy Trading and Market Regulation",
    titleAr: "تجارة الطاقة وتنظيم السوق",
    contentEn: "MOEI plays a central role in regulating energy trading activities within the UAE, ensuring fair market practices, price transparency, and supply security. The ministry oversees the wholesale electricity market, natural gas trading, and petroleum product distribution. Energy trading licenses are required for any entity engaged in the buying, selling, or brokering of energy commodities.\n\nThe UAE Wholesale Electricity Market, regulated by MOEI, enables power generators and distributors to trade electricity through a competitive market mechanism. Market participants must be licensed and comply with the Market Rules and Grid Code published by MOEI. The market operates with day-ahead and real-time trading windows, with settlements managed through the market operator. Price caps and floors are established to prevent market manipulation while allowing competitive pricing.\n\nNatural gas trading falls under MOEI's regulatory framework, which aligns with international best practices. The ministry coordinates with ADNOC and other national energy companies to ensure adequate domestic gas supply while enabling export capacity. Energy traders must maintain compliance with anti-money laundering regulations and report significant transactions as required by UAE financial regulations.",
    contentAr: "تلعب وزارة الطاقة والبنية التحتية دوراً محورياً في تنظيم أنشطة تجارة الطاقة في الإمارات، مما يضمن ممارسات السوق العادلة وشفافية الأسعار وأمن الإمدادات. تشرف الوزارة على سوق الكهرباء بالجملة وتجارة الغاز الطبيعي وتوزيع المنتجات البترولية. تتطلب تراخيص تجارة الطاقة لأي كيان يمارس شراء أو بيع أو وساطة السلع الطاقية.\n\nسوق الكهرباء بالجملة الإماراتي، الذي تنظمه الوزارة، يمكن منتجي وموزعي الكهرباء من التداول من خلال آلية سوق تنافسية. يجب على مشاركي السوق الحصول على ترخيص والامتثال لقواعد السوق ومدونة الشبكة المنشورة من الوزارة. يعمل السوق بنوافذ التداول اليومية وفي الوقت الفعلي، مع تسوية المدفوعات من خلال مشغل السوق. يتم تحديد سقوف وأرضيات الأسعار لمنع التلاعب بالسوق مع السماح بالتسعير التنافسي.\n\nتخضع تجارة الغاز الطبيعي للإطار التنظيمي للوزارة، الذي يتوافق مع أفضل الممارسات الدولية. تنسق الوزارة مع أدنوك وشركات الطاقة الوطنية الأخرى لضمان إمدادات الغاز المحلية الكافية مع تمكين القدرة التصديرية. يجب على متداولي الطاقة الحفاظ على الامتثال لأنظمة مكافحة غسل الأموال والإبلاغ عن المعاملات الكبيرة كما تتطلب اللوائح المالية الإماراتية.",
    category: "Petroleum & Energy",
    tags: "energy trading, market, electricity market, gas, regulation, wholesale"
  },
  {
    id: "kb-petrol-004",
    titleEn: "Mining and Quarrying Regulations",
    titleAr: "لوائح التعدين والمحاجر",
    contentEn: "MOEI regulates mining and quarrying activities on federal lands in the UAE. This includes the extraction of construction materials (sand, gravel, limestone), industrial minerals, and any mineral exploration activities. Companies must obtain a mining license from MOEI before commencing any extraction activities on federal land. The licensing process includes environmental impact assessment, operational plan review, and financial guarantee requirements.\n\nMining licenses are issued for specific minerals and defined geographic areas. The standard license period is 5 years, renewable upon demonstration of compliance with all terms and conditions. License holders must implement environmental management plans, including land reclamation and rehabilitation commitments. Progressive reclamation is required — areas where extraction is complete must be rehabilitated within 12 months.\n\nQuarrying operations must comply with MOEI's safety standards, including blast management plans, dust control measures, and groundwater protection protocols. Buffer zones of at least 500 meters from residential areas are mandatory for all blasting operations. Transport routes for extracted materials must be approved by MOEI and coordinated with local traffic authorities. Violations of mining regulations can result in fines, license suspension, or permanent revocation.",
    contentAr: "تنظم وزارة الطاقة والبنية التحتية أنشطة التعدين والمحاجر في الأراضي الاتحادية في الإمارات. يشمل ذلك استخراج مواد البناء (الرمل والحصى والحجر الجيري)، المعادن الصناعية، وأي أنشطة استكشاف معدني. يجب على الشركات الحصول على رخصة تعدين من الوزارة قبل البدء في أي أنشطة استخراج على الأراضي الاتحادية. تشمل عملية الترخيص تقييم الأثر البيئي ومراجعة الخطة التشغيلية ومتطلبات الضمان المالي.\n\nتُصدر تراخيص التعدين لمعادن محددة ومناطق جغرافية محددة. مدة الترخيص القياسية هي 5 سنوات، قابلة للتجديد عند إثبات الامتثال لجميع الشروط والأحكام. يجب على حاملي التراخيص تنفيذ خطط الإدارة البيئية، بما في ذلك التزامات استصلاح وإعادة تأهيل الأراضي. الاستصلاح التدريجي مطلوب — يجب إعادة تأهيل المناطق التي اكتمل الاستخراج منها خلال 12 شهراً.\n\nيجب أن تتوافق عمليات المحاجر مع معايير سلامة الوزارة، بما في ذلك خطط إدارة التفجير وتدابير مكافحة الغبار وبروتوكولات حماية المياه الجوفية. المناطق العازلة التي لا تقل عن 500 متر من المناطق السكنية إلزامية لجميع عمليات التفجير. يجب الموافقة على مسارات نقل المواد المستخرجة من الوزارة وتنسيقها مع سلطات المرور المحلية. قد يؤدي انتهاك لوائح التعدين إلى غرامات أو تعليق الترخيص أو الإلغاء الدائم.",
    category: "Petroleum & Energy",
    tags: "mining, quarrying, extraction, minerals, environmental, license"
  },

  // ============================================================
  // TRANSPORT (3 articles)
  // ============================================================
  {
    id: "kb-transport-001",
    titleEn: "Land Transport Licensing",
    titleAr: "ترخيص النقل البري",
    contentEn: "MOEI issues and regulates land transport licenses for commercial freight and passenger transport services operating on federal roads in the UAE. Transport companies must obtain the appropriate license category based on their operations: Light Transport (vehicles under 3.5 tons), Heavy Transport (vehicles over 3.5 tons), Passenger Transport (taxis, buses, and limousines), and Specialized Transport (hazardous materials, oversized loads, temperature-controlled).\n\nLicense applicants must provide company registration documents, vehicle registration and inspection certificates, driver qualification documents, insurance certificates, and an operational plan. The standard license is valid for one year and must be renewed annually. All licensed vehicles must pass MOEI safety inspections and display valid transport stickers. Drivers must hold valid UAE driving licenses appropriate for their vehicle class and undergo periodic training.\n\nMOEI monitors compliance through roadside inspections, GPS tracking requirements for heavy vehicles, and periodic audits of transport companies. Violations such as overloading, driver fatigue, inadequate vehicle maintenance, or operating without a valid license result in fines ranging from AED 5,000 to AED 200,000 and potential license revocation. The ministry also handles complaints about transport services at 8005555.",
    contentAr: "تصدر وزارة الطاقة والبنية التحتية وتنظم تراخيص النقل البري لخدمات الشحن التجاري ونقل الركاب التي تعمل على الطرق الاتحادية في الإمارات. يجب على شركات النقل الحصول على فئة الترخيص المناسبة بناءً على عملياتها: النقل الخفيف (مركبات أقل من 3.5 طن)، النقل الثقيل (مركبات أكثر من 3.5 طن)، نقل الركاب (سيارات الأجرة والحافلات والليموزين)، والنقل المتخصص (مواد خطرة، أحمال كبيرة، مبردة).\n\nيجب على المتقدمين للترخيص تقديم مستندات تسجيل الشركة وشهادات تسجيل وفحص المركبات ومستندات مؤهلات السائقين وشهادات التأمين وخطة تشغيلية. الترخيص القياسي صالح لمدة سنة واحدة ويجب تجديده سنوياً. يجب أن تجتاز جميع المركبات المرخصة عمليات تفتيش السلامة من الوزارة وعرض ملصقات نقل صالحة. يجب أن يحمل السائقون رخص قيادة إماراتية سارية مناسبة لفئة مركبتهم ويخضعون لتدريب دوري.\n\nتراقب الوزارة الامتثال من خلال عمليات التفتيش على جانب الطريق ومتطلبات تتبع GPS للمركبات الثقيلة والتدقيق الدوري لشركات النقل. الانتهاكات مثل التحميل الزائد أو إرهاق السائق أو الصيانة غير الكافية أو العمل بدون ترخيص ساري تؤدي إلى غرامات تتراوح من 5,000 إلى 200,000 درهم واحتمال إلغاء الترخيص. كما تتولى الوزارة الشكاوى حول خدمات النقل على 8005555.",
    category: "Transport",
    tags: "land transport, licensing, freight, passenger, commercial, vehicle"
  },
  {
    id: "kb-transport-002",
    titleEn: "Maritime Services and Regulation",
    titleAr: "الخدمات البحرية والتنظيم",
    contentEn: "MOEI oversees maritime transport services and infrastructure at UAE federal ports and waters. This includes regulation of commercial vessel operations, port facility management, maritime safety standards, and coordination with local maritime authorities. The ministry works to ensure that UAE maritime operations comply with international conventions including SOLAS, MARPOL, and the STCW Convention.\n\nMaritime service licenses are required for companies operating commercial vessels, ferry services, and maritime support operations in federal waters. The licensing process involves verification of vessel safety certificates, crew qualifications, insurance coverage, and environmental compliance. MOEI coordinates with the National Transport Authority and local port authorities to streamline regulatory processes.\n\nMaritime safety is a top priority for MOEI. The ministry mandates regular vessel inspections, enforces crew competency standards, and maintains maritime incident reporting requirements. All vessels operating in UAE federal waters must carry valid safety equipment, maintain communication protocols, and comply with navigation rules. Maritime incidents, including groundings, collisions, and pollution events, must be reported to MOEI within 24 hours.",
    contentAr: "تشرف وزارة الطاقة والبنية التحتية على خدمات النقل البحري والبنية التحتية في الموانئ الاتحادية والمياه الإماراتية. يشمل ذلك تنظيم عمليات السفن التجارية وإدارة مرافق الموانئ ومعايير السلامة البحرية والتنسيق مع السلطات البحرية المحلية. تعمل الوزارة على ضمان امتثال العمليات البحرية الإماراتية للاتفاقيات الدولية بما في ذلك سولاس وماربول واتفاقية STCW.\n\nتراخيص الخدمات البحرية مطلوبة للشركات التي تشغل سفناً تجارية وخدمات عبّار وعمليات دعم بحري في المياه الاتحادية. تشمل عملية الترخيص التحقق من شهادات سلامة السفينة ومؤهلات الطاقم والتأمين والامتثال البيئي. تنسق الوزارة مع الهيئة الوطنية للنقل وسلطات الموانئ المحلية لتبسيط العمليات التنظيمية.\n\nالسلامة البحرية هي أولوية قصوى للوزارة. تفرض الوزارة عمليات تفتيش دورية للسفن وتنفذ معايير كفاءة الطاقم وتحافظ على متطلبات الإبلاغ عن الحوادث البحرية. يجب على جميع السفن التي تعمل في المياه الاتحادية الإماراتية حمل معدات سلامة صالحة والحفاظ على بروتوكولات الاتصال والامتثال لقواعد الملاحة. يجب الإبلاغ عن الحوادث البحرية، بما في ذلك جنوح السفن والتصادمات وحوادث التلوث، للوزارة خلال 24 ساعة.",
    category: "Transport",
    tags: "maritime, port, vessel, safety, regulation, commercial, ferry"
  },
  {
    id: "kb-transport-003",
    titleEn: "Transport Safety Regulations",
    titleAr: "لوائح سلامة النقل",
    contentEn: "MOEI establishes and enforces safety regulations for all modes of transport under federal jurisdiction, including road, maritime, and rail transport. The safety regulatory framework covers vehicle and vessel safety standards, operator qualifications, hazardous materials transport, and incident investigation. All transport operators must develop and maintain a Safety Management System (SMS) approved by MOEI.\n\nFor road transport, key safety requirements include mandatory rest periods for commercial drivers (maximum 9 hours driving per day with mandatory 30-minute breaks every 4 hours), vehicle maintenance schedules, load securing standards, and speed limiter requirements for heavy vehicles. All commercial vehicles must be equipped with GPS tracking and event data recorders. MOEI conducts unannounced safety inspections at transport terminals and on federal highways.\n\nHazardous materials transport requires specialized licensing and compliance with the UAE Hazardous Materials Transport Code. Vehicles must display appropriate hazard placards, carry emergency response kits, and be driven by certified HAZMAT drivers. Route restrictions apply for hazardous materials transport through residential areas and tunnels. MOEI investigates all transport incidents involving injuries, fatalities, or environmental damage, and publishes safety bulletins with lessons learned.",
    contentAr: "تضع وزارة الطاقة والبنية التحتية وتنفذ لوائح السلامة لجميع وسائل النقل تحت الاختصاص الاتحادي، بما في ذلك النقل البري والبحري والسككي. يغطي الإطار التنظيمي للسلامة معايير سلامة المركبات والسفن ومؤهلات المشغلين ونقل المواد الخطرة وتحقيق الحوادث. يجب على جميع مشغلي النقل تطوير والحفاظ على نظام إدارة السلامة المعتمد من الوزارة.\n\nللنقل البري، تشمل متطلبات السلامة الرئيسية فترات الراحة الإلزامية للسائقين التجاريين (حد أقصى 9 ساعات قيادة يومياً مع استراحات إلزامية 30 دقيقة كل 4 ساعات)، جداول صيانة المركبات، معايير تثبيت الأحمال، ومتطلبات محددات السرعة للمركبات الثقيلة. يجب تجهيز جميع المركبات التجارية بتتبع GPS ومسجلات بيانات الأحداث. تجري الوزارة عمليات تفتيش سلامة مفاجئة في محطات النقل وعلى الطرق السريعة الاتحادية.\n\nيتطلب نقل المواد الخطرة ترخيصاً متخصصاً والامتثال لمدونة نقل المواد الخطرة الإماراتية. يجب أن تعرض المركبات لوحات خطر مناسبة وتحمل مجموعات الاستجابة للطوارئ ويقودها سائقون معتمدون للمواد الخطرة. تنطبق قيود المسار على نقل المواد الخطرة عبر المناطق السكنية والأنفاق. تحقق الوزارة في جميع حوادث النقل التي تنطوي على إصابات أو وفيات أو أضرار بيئية وتنشر نشرات سلامة بالدروس المستفادة.",
    category: "Transport",
    tags: "safety, transport, regulation, hazmat, driver, vehicle, inspection"
  },

  // ============================================================
  // GENERAL SERVICES (5 articles)
  // ============================================================
  {
    id: "kb-general-001",
    titleEn: "UAE PASS Digital Identity",
    titleAr: "الهوية الرقمية UAE PASS",
    contentEn: "UAE PASS is the national digital identity platform required for accessing MOEI and all UAE government services online. It provides secure single sign-on authentication, digital signatures, and document sharing capabilities. All MOEI online services, from applying for electricity connections to tracking housing applications, require UAE PASS login.\n\nTo register for UAE PASS, visit www.uaepass.ae or download the UAE PASS mobile app. Registration requires a valid Emirates ID and a UAE mobile number. The setup process includes identity verification through facial recognition and one-time password (OTP) confirmation. Once registered, you can use UAE PASS to access over 6,000 government services across all emirates.\n\nUAE PASS supports digital signatures that have legal validity equivalent to handwritten signatures under UAE Federal Law. You can use UAE PASS to sign MOEI applications, contracts, and other official documents electronically. The platform also stores verified digital copies of your official documents (Emirates ID, driving license, etc.) that can be shared with government entities without needing physical copies. For UAE PASS technical support, call 600 561 111.",
    contentAr: "UAE PASS هي منصة الهوية الرقمية الوطنية المطلوبة للوصول إلى خدمات الوزارة وجميع خدمات الحكومة الإماراتية عبر الإنترنت. توفر مصادقة تسجيل دخول موحد آمنة وتوقيعات رقمية وإمكانيات مشاركة المستندات. جميع خدمات الوزارة عبر الإنترنت، من التقديم لتوصيل الكهرباء إلى متابعة طلبات الإسكان، تتطلب تسجيل الدخول عبر UAE PASS.\n\nللتسجيل في UAE PASS، قم بزيارة www.uaepass.ae أو تحميل تطبيق UAE PASS المحمول. يتطلب التسجيل هوية إماراتية سارية ورقم هاتف محمول إماراتي. تشمل عملية الإعداد التحقق من الهوية من خلال التعرف على الوجه وتأكيد كلمة المرور لمرة واحدة. بعد التسجيل، يمكنك استخدام UAE PASS للوصول إلى أكثر من 6,000 خدمة حكومية في جميع الإمارات.\n\nيدعم UAE PASS التوقيعات الرقمية التي لها صلاحية قانونية معادلة للتوقيعات اليدوية بموجب القانون الاتحادي الإماراتي. يمكنك استخدام UAE PASS لتوقيع طلبات الوزارة والعقود والمستندات الرسمية الأخرى إلكترونياً. كما تخزن المنطقة نسخاً رقمية موثقة من مستنداتك الرسمية (الهوية الإماراتية، رخصة القيادة، إلخ) التي يمكن مشاركتها مع الجهات الحكومية دون الحاجة لنسخ ورقية. للدعم الفني لـ UAE PASS، اتصل على 600 561 111.",
    category: "General Services",
    tags: "uae pass, digital identity, login, authentication, digital signature"
  },
  {
    id: "kb-general-002",
    titleEn: "MOEI Fee Schedule",
    titleAr: "جدول رسوم وزارة الطاقة والبنية التحتية",
    contentEn: "MOEI publishes a comprehensive fee schedule for all its services, available on www.moei.gov.ae. Fees are regulated by federal decree and are standardized across all emirates for federal services. The fee schedule covers electricity and water services, housing programs, petroleum licensing, transport licensing, and other regulatory services. Payment can be made online, at service centers, or through approved payment channels.\n\nKey service fees include: Electricity connection (residential) AED 1,500, Water connection (residential) AED 1,000, Housing loan application AED 500, Petroleum exploration license AED 50,000, Heavy transport license AED 10,000 per vehicle, Building permit review AED 5,000. Fee exemptions apply for certain categories including people of determination, senior citizens over 60, and low-income families as defined by federal guidelines.\n\nFee disputes can be raised through the formal complaints process. Requests for fee waivers for financial hardship are reviewed on a case-by-case basis by the MOEI Fee Review Committee. Government entities and charitable organizations may qualify for reduced or waived fees. The fee schedule is updated annually and any changes are announced 30 days before implementation through the MOEI website and official gazette.",
    contentAr: "تنشر وزارة الطاقة والبنية التحتية جدول رسوم شامل لجميع خدماتها، متاح على www.moei.gov.ae. تنظم الرسوم بموجب مرسوم اتحادي وهي موحدة في جميع الإمارات للخدمات الاتحادية. يغطي جدول الرسوم خدمات الكهرباء والمياه وبرامج الإسكان وترخيص البترول وترخيص النقل والخدمات التنظيمية الأخرى. يمكن الدفع عبر الإنترنت أو في مراكز الخدمة أو من خلال قنوات الدفع المعتمدة.\n\nتشمل رسوم الخدمات الرئيسية: توصيل الكهرباء (سكني) 1,500 درهم، توصيل المياه (سكني) 1,000 درهم، طلب القرض الإسكاني 500 درهم، رخصة استكشاف البترول 50,000 درهم، ترخيص النقل الثقيل 10,000 درهم لكل مركبة، مراجعة تصريح البناء 5,000 درهم. تنطبق إعفاءات الرسوم على فئات معينة بما في ذلك أصحاب الهمم وكبار السن فوق 60 عاماً والأسر ذات الدخل المحدود كما تحدد المبادئ التوجيهية الاتحادية.\n\nيمكن الاعتراض على الرسوم من خلال عملية الشكاوى الرسمية. تتم مراجعة طلبات الإعفاء من الرسوم للصعوبات المالية على أساس كل حالة على حدة من قبل لجنة مراجعة الرسوم بالوزارة. قد تأهل الكيانات الحكومية والمنظمات الخيرية لرسوم مخفضة أو معفاة. يتم تحديث جدول الرسوم سنوياً وأي تغييرات يتم الإعلان عنها قبل 30 يوماً من التنفيذ عبر موقع الوزارة والجريدة الرسمية.",
    category: "General Services",
    tags: "fees, schedule, payment, pricing, services, waiver"
  },
  {
    id: "kb-general-003",
    titleEn: "MOEI Office Hours and Locations",
    titleAr: "ساعات العمل ومواقع وزارة الطاقة والبنية التحتية",
    contentEn: "MOEI service centers operate Sunday through Thursday from 7:30 AM to 2:30 PM (UAE local time, GMT+4). The main headquarters is located in Abu Dhabi, with additional service centers in Dubai, Sharjah, Ajman, Umm Al Quwain, Ras Al Khaimah, and Fujairah. All service centers provide the full range of MOEI services including application submissions, document verification, and fee payments.\n\nThe MOEI Customer Happiness Centers provide extended services including walk-in consultations, application assistance, and priority services for people of determination and senior citizens. During Ramadan, office hours are adjusted to 9:00 AM to 2:00 PM. Online services through www.moei.gov.ae are available 24/7, and the customer service hotline (8005555) operates during office hours with an automated system for after-hours inquiries.\n\nAppointments can be booked online to reduce waiting times. Walk-in customers are served on a first-come, first-served basis with estimated waiting times displayed at each center. Each center is equipped with self-service kiosks for common transactions such as bill payment, application status checks, and document printing. Parking is available at all locations with designated spaces for people of determination.",
    contentAr: "تعمل مراكز خدمة وزارة الطاقة والبنية التحتية من الأحد إلى الخميس من 7:30 صباحاً إلى 2:30 مساءً (التوقيت المحلي الإماراتي، GMT+4). يقع المقر الرئيسي في أبوظبي، مع مراكز خدمة إضافية في دبي والشارقة وعجمان وأم القيوين ورأس الخيمة والفجيرة. جميع مراكز الخدمة توفر المجموعة الكاملة من خدمات الوزارة بما في ذلك تقديم الطلبات والتحقق من المستندات ودفع الرسوم.\n\nتوفر مراكز سعادة المتعاملين خدمات موسعة تشمل استشارات بدون موعد ومساعدة في التقديم وخدمات أولوية لأصحاب الهمم وكبار السن. خلال شهر رمضان، يتم تعديل ساعات العمل إلى 9:00 صباحاً - 2:00 مساءً. الخدمات عبر الإنترنت من خلال www.moei.gov.ae متاحة على مدار الساعة، وخط خدمة العملاء (8005555) يعمل خلال ساعات العمل مع نظام آلي للاستفسارات بعد ساعات العمل.\n\nيمكن حجز المواعيد عبر الإنترنت لتقليل أوقات الانتظار. يتم خدمة العملاء بدون موعد حسب أسبقية الوصول مع عرض أوقات الانتظار المقدرة في كل مركز. كل مركز مجهز بأكشاك الخدمة الذكية للمعاملات الشائعة مثل دفع الفواتير والتحقق من حالة الطلبات وطباعة المستندات. يتوفر موقف سيارات في جميع المواقع مع أماكن مخصصة لأصحاب الهمم.",
    category: "General Services",
    tags: "office hours, locations, service center, customer happiness, appointment"
  },
  {
    id: "kb-general-004",
    titleEn: "Contact MOEI: Phone, Email, and Online",
    titleAr: "التواصل مع الوزارة: الهاتف والبريد الإلكتروني والإنترنت",
    contentEn: "MOEI provides multiple contact channels for customer inquiries and support. The main customer service hotline is 8005555, available Sunday through Thursday from 7:30 AM to 2:30 PM. For electricity emergencies, call 997 (24/7). For water emergencies, call 998 (24/7). These emergency lines are toll-free and operate around the clock.\n\nOnline services are available 24/7 at www.moei.gov.ae, where customers can submit applications, track requests, pay bills, and access self-service tools. Email inquiries can be sent to info@moei.gov.ae for general questions. For specific department inquiries, contact details are listed on the MOEI website. The MOEI social media accounts on X (Twitter) @MOEI_UAE and Instagram @moei_uae provide updates and can address general inquiries.\n\nFor formal complaints and suggestions, use the online complaint form on the MOEI website or visit a Customer Happiness Center in person. Complaints are acknowledged within 2 working days and resolved within 10-15 working days depending on complexity. MOEI is committed to the UAE Customer Happiness Index standards and follows up on all complaints until resolution. Feedback can also be provided through the MOEI mobile app.",
    contentAr: "توفر وزارة الطاقة والبنية التحتية قنوات اتصال متعددة لاستفسارات العملاء والدعم. خط خدمة العملاء الرئيسي هو 8005555، متاح من الأحد إلى الخميس من 7:30 صباحاً إلى 2:30 مساءً. لحالات الطوارئ الكهربائية، اتصل على 997 (24/7). لحالات الطوارئ المائية، اتصل على 998 (24/7). هذه الخطوط الطارئة مجانية وتعمل على مدار الساعة.\n\nالخدمات عبر الإنترنت متاحة على مدار الساعة على www.moei.gov.ae، حيث يمكن للعملاء تقديم الطلبات ومتابعة الطلبات ودفع الفواتير والوصول إلى أدوات الخدمة الذكية. يمكن إرسال استفسارات البريد الإلكتروني إلى info@moei.gov.ae للأسئلة العامة. لاستفسارات الإدارات المحددة، تفاصيل الاتصال مدرجة على موقع الوزارة. حسابات الوزارة على وسائل التواصل الاجتماعي على X (تويتر) @MOEI_UAE وانستغرام @moei_uae توفر تحديثات ويمكنها معالجة الاستفسارات العامة.\n\nللشكاوى والاقتراحات الرسمية، استخدم نموذج الشكوى عبر الإنترنت على موقع الوزارة أو قم بزيارة مركز سعادة المتعاملين شخصياً. يتم الإقرار باستلام الشكاوى خلال يومي عمل وحلها خلال 10-15 يوم عمل حسب التعقيد. تلتزم الوزارة بمعايير مؤشر سعادة المتعاملين الإماراتي وتتابع جميع الشكاوى حتى الحل. يمكن أيضاً تقديم الملاحظات من خلال تطبيق الوزارة المحمول.",
    category: "General Services",
    tags: "contact, phone, email, 8005555, 997, 998, website, complaint"
  },
  {
    id: "kb-general-005",
    titleEn: "Complaint and Feedback Procedures",
    titleAr: "إجراءات الشكاوى والملاحظات",
    contentEn: "MOEI has a structured complaint and feedback process to ensure customer satisfaction and continuous service improvement. Complaints can be submitted through multiple channels: online via www.moei.gov.ae, by calling 8005555, by email to info@moei.gov.ae, or in person at any Customer Happiness Center. All complaints receive a unique tracking number for monitoring progress.\n\nUpon receipt, complaints are categorized by type (service quality, billing, delay, staff behavior, policy concern) and priority (urgent, high, medium, low). Urgent complaints involving safety or service disruption are escalated immediately to senior management. Standard complaints are acknowledged within 2 working days and resolved within 10 working days. Complex complaints requiring investigation may take up to 30 working days, with interim updates provided every 5 working days.\n\nIf you are unsatisfied with the resolution, you can escalate to the MOEI Complaint Review Committee within 15 days of receiving the response. The committee reviews the case independently and provides a final decision within 15 working days. MOEI also welcomes positive feedback and suggestions for service improvement, which can be submitted through the same channels. All feedback is analyzed to identify systemic issues and improvement opportunities.",
    contentAr: "لدى وزارة الطاقة والبنية التحتية عملية منظمة للشكاوى والملاحظات لضمان رضا العملاء والتحسين المستمر للخدمات. يمكن تقديم الشكاوى عبر قنوات متعددة: عبر الإنترنت على www.moei.gov.ae، بالاتصال على 8005555، بالبريد الإلكتروني إلى info@moei.gov.ae، أو شخصياً في أي مركز سعادة المتعاملين. تتلقى جميع الشكاوى رقماً مرجعياً فريداً لمتابعة التقدم.\n\nعند الاستلام، يتم تصنيف الشكاوى حسب النوع (جودة الخدمة، الفواتير، التأخير، سلوك الموظفين، مخاوف سياسية) والأولوية (عاجلة، عالية، متوسطة، منخفضة). يتم تصعيد الشكاوى العاجلة المتعلقة بالسلامة أو انقطاع الخدمة فوراً إلى الإدارة العليا. يتم الإقرار بالشكاوى القياسية خلال يومي عمل وحلها خلال 10 أيام عمل. الشكاوى المعقدة التي تتطلب تحقيقاً قد تستغرق حتى 30 يوم عمل، مع تحديثات مرحلية كل 5 أيام عمل.\n\nإذا كنت غير راضٍ عن الحل، يمكنك التصعيد إلى لجنة مراجعة الشكاوى بالوزارة خلال 15 يوماً من استلام الرد. تراجع اللجنة القضية بشكل مستقل وتقدم قراراً نهائياً خلال 15 يوم عمل. كما ترحب الوزارة بالملاحظات الإيجابية واقتراحات تحسين الخدمة، والتي يمكن تقديمها من خلال نفس القنوات. يتم تحليل جميع الملاحظات لتحديد المشاكل النظامية وفرص التحسين.",
    category: "General Services",
    tags: "complaint, feedback, escalation, tracking, resolution, customer satisfaction"
  },

  // ============================================================
  // SUSTAINABILITY (5 articles)
  // ============================================================
  {
    id: "kb-sustain-001",
    titleEn: "UAE Energy Strategy 2050",
    titleAr: "استراتيجية الطاقة الإماراتية 2050",
    contentEn: "The UAE Energy Strategy 2050 is the national roadmap for transforming the UAE's energy sector, targeting a 44% share of clean energy in the national energy mix by 2050. Launched under the vision of the UAE leadership, the strategy aims to balance economic growth with environmental sustainability. Key targets include reducing carbon emissions by 70%, increasing renewable energy capacity to 44%, and improving energy efficiency by 40% compared to business-as-usual scenarios.\n\nMOEI is the primary federal entity responsible for implementing the strategy, coordinating with emirate-level authorities, and monitoring progress toward targets. The strategy encompasses clean energy projects including the Barakah Nuclear Energy Plant, Mohammed bin Rashid Al Maktoum Solar Park, and numerous distributed solar installations. Investment in the energy transition is estimated at AED 600 billion by 2050.\n\nThe strategy also addresses energy storage, grid modernization, smart infrastructure, and workforce development for the clean energy sector. MOEI publishes annual progress reports and updates the strategy periodically to reflect technological advances and changing market conditions. Citizens and businesses can contribute to the strategy's goals through energy efficiency measures, renewable energy adoption, and participation in MOEI's sustainability programs.",
    contentAr: "استراتيجية الطاقة الإماراتية 2050 هي خارطة الطريق الوطنية لتحويل قطاع الطاقة في الإمارات، باستهداف حصة 44% من الطاقة النظيفة في مزيج الطاقة الوطني بحلول 2050. أطلقت برؤية القيادة الإماراتية، وتسعى الاستراتيجية لتحقيق التوازن بين النمو الاقتصادي والاستدامة البيئية. تشمل الأهداف الرئيسية تقليل انبعاثات الكربون بنسبة 70%، وزيادة قدرة الطاقة المتجددة إلى 44%، وتحسين كفاءة الطاقة بنسبة 40% مقارنة بالسيناريوهات الاعتيادية.\n\nوزارة الطاقة والبنية التحتية هي الجهة الاتحادية الرئيسية المسؤولة عن تنفيذ الاستراتيجية والتنسيق مع السلطات على مستوى الإمارات ومراقبة التقدم نحو الأهداف. تشمل الاستراتيجية مشاريع الطاقة النظيفة بما في ذلك محطة براكة للطاقة النووية ومحمد بن راشد آل مكتوم للطاقة الشمسية والعديد من تركيبات الطاقة الشمسية الموزعة. يُقدر الاستثمار في التحول الطاقي بنحو 600 مليار درهم بحلول 2050.\n\nتتناول الاستراتيجية أيضاً تخزين الطاقة وتحديث الشبكة والبنية التحتية الذكية وتطوير القوى العاملة لقطاع الطاقة النظيفة. تنشر الوزارة تقارير تقدم سنوية وتحدث الاستراتيجية دورياً لتعكس التقدم التكنولوجي وتغير ظروف السوق. يمكن للمواطنين والشركات المساهمة في أهداف الاستراتيجية من خلال إجراءات كفاءة الطاقة وتبني الطاقة المتجددة والمشاركة في برامج الاستدامة للوزارة.",
    category: "Sustainability",
    tags: "energy strategy 2050, clean energy, carbon reduction, renewable, sustainability"
  },
  {
    id: "kb-sustain-002",
    titleEn: "Green Building Standards",
    titleAr: "معايير البناء الأخضر",
    contentEn: "MOEI promotes green building practices in line with the UAE's commitment to sustainable development. Federal buildings must achieve a minimum 2-pearl rating under the Estidama Pearl Rating System or equivalent certification (such as LEED Gold). MOEI provides guidelines for energy-efficient building design, water conservation systems, waste management during construction, and the use of sustainable materials.\n\nKey green building requirements for federal projects include: minimum 30% reduction in energy consumption compared to standard buildings, water use reduction of at least 40%, on-site renewable energy generation where feasible, and indoor environmental quality standards. Building envelopes must meet enhanced insulation and glazing standards to minimize cooling loads. All major federal construction projects must undergo a life-cycle cost analysis demonstrating long-term sustainability benefits.\n\nFor private developers, MOEI offers technical guidance and incentives for voluntary green building certification. The ministry also runs awareness programs about green building benefits, including reduced operating costs, improved occupant health and productivity, and higher property values. Green building workshops and training programs are offered regularly in partnership with industry associations and academic institutions.",
    contentAr: "تشجع وزارة الطاقة والبنية التحتية ممارسات البناء الأخضر تتوافقاً مع التزام الإمارات بالتنمية المستدامة. يجب أن تحقق المباني الاتحادية تصنيف لؤلؤتين كحد أدنى ضمن نظام تصنيف استدامة أو شهادة معادلة (مثل LEED Gold). تقدم الوزارة إرشادات لتصميم المباني الموفرة للطاقة وأنظمة ترشيد استهلاك المياه وإدارة النفايات أثناء البناء واستخدام المواد المستدامة.\n\nتشمل متطلبات البناء الأخضر الرئيسية للمشاريع الاتحادية: الحد الأدنى لتخفيض استهلاك الطاقة بنسبة 30% مقارنة بالمباني القياسية، وتخفيض استخدام المياه بنسبة 40% على الأقل، وتوليد الطاقة المتجددة في الموقع حيثما أمكن، ومعايير جودة البيئة الداخلية. يجب أن تلبي غلاف المباني معايير العزل والزجاج المحسنة لتقليل أحمال التبريد. يجب أن تخضع جميع مشاريع البناء الاتحادية الكبرى لتحليل تكلفة دورة الحياة الذي يوضح فوائد الاستدامة طويلة المدى.\n\nللمطورين الخاصين، تقدم الوزارة إرشادات فنية وحوافز لشهادة البناء الأخضر الطوعية. كما تدير الوزارة برامج توعية حول فوائد البناء الأخضر، بما في ذلك تقليل التكاليف التشغيلية وتحسين صحة وإنتاجية شاغلي المبنى وزيادة قيم العقار. تُقدم ورش عمل البناء الأخضر وبرامج التدريب بانتظام بالشراكة مع جمعيات الصناعة والمؤسسات الأكاديمية.",
    category: "Sustainability",
    tags: "green building, estidama, LEED, sustainability, energy efficiency, federal building"
  },
  {
    id: "kb-sustain-003",
    titleEn: "Carbon Reduction Initiatives",
    titleAr: "مبادرات تقليل الكربون",
    contentEn: "MOEI leads federal carbon reduction initiatives as part of the UAE's commitment to achieving net-zero emissions by 2050. The ministry coordinates the National Carbon Emissions Registry, which tracks emissions from major industrial facilities and power plants. Companies emitting over 25,000 tonnes of CO2 equivalent annually are required to report their emissions to MOEI and participate in emission reduction programs.\n\nKey carbon reduction programs include the Carbon Capture, Utilization, and Storage (CCUS) initiative, which supports the development of technologies to capture CO2 from industrial processes. MOEI also promotes fuel switching from heavy fuel oil to natural gas and renewable energy, energy efficiency improvements in industrial processes, and the adoption of electric vehicles for government fleets. The UAE was the first country in the region to commit to the Paris Agreement goals.\n\nBusinesses can participate in MOEI's carbon reduction programs through voluntary emission reporting, implementing energy efficiency measures, and investing in renewable energy. MOEI provides technical assistance, carbon accounting tools, and recognition through the UAE Green Business Certification program. The ministry also facilitates participation in international carbon markets and voluntary offset programs for companies seeking to achieve carbon neutrality.",
    contentAr: "تقود وزارة الطاقة والبنية التحتية مبادرات تقليل الكربون الاتحادية كجزء من التزام الإمارات بتحقيق صافي انبعاثات صفرية بحلول 2050. تنسق الوزارة السجل الوطني لانبعاثات الكربون، الذي يتتبع الانبعاثات من المرافق الصناعية الكبرى ومحطات الطاقة. يجب على الشركات التي تنبعث أكثر من 25,000 طن مكافئ من ثاني أكسيد الكربون سنوياً الإبلاغ عن انبعاثاتها للوزارة والمشاركة في برامج تقليل الانبعاثات.\n\nتشمل برامج تقليل الكربون الرئيسية مبادرة التقاط الكربون واستخدامه وتخزينه (CCUS)، التي تدعم تطوير التقنيات لالتقاط ثاني أكسيد الكربون من العمليات الصناعية. كما تشجع الوزارة التحول من الوقود الثقيل إلى الغاز الطبيعي والطاقة المتجددة وتحسين كفاءة الطاقة في العمليات الصناعية وتبني المركبات الكهربائية لأساطيل الحكومة. كانت الإمارات أول دولة في المنطقة تلتزم بأهداف اتفاقية باريس.\n\nيمكن للشركات المشاركة في برامج تقليل الكربون من خلال الإبلاغ الطوعي عن الانبعاثات وتنفيذ إجراءات كفاءة الطاقة والاستثمار في الطاقة المتجددة. تقدم الوزارة مساعدة فنية وأدوات محاسبة الكربون وتقدير من خلال برنامج شهادة الأعمال الخضراء الإماراتية. كما تسهل الوزارة المشاركة في أسواق الكربون الدولية وبرامج التعويض الطوعية للشركات التي تسعى لتحقيق الحياد الكربوني.",
    category: "Sustainability",
    tags: "carbon reduction, net zero, CCUS, emissions, paris agreement, carbon neutrality"
  },
  {
    id: "kb-sustain-004",
    titleEn: "Water Conservation and Sustainability",
    titleAr: "ترشيد واستدامة المياه",
    contentEn: "Water conservation is a critical priority for MOEI given the UAE's arid climate and limited natural freshwater resources. The UAE has one of the highest per-capita water consumption rates globally, making conservation essential. MOEI's water sustainability programs target a 40% reduction in residential water consumption by 2030 through efficiency standards, awareness campaigns, and smart technology deployment.\n\nMOEI mandates water-efficient fixtures in all new federal buildings, including low-flow faucets, dual-flush toilets, and water-efficient landscaping (xeriscaping). The ministry promotes treated sewage effluent (TSE) reuse for irrigation and industrial cooling, reducing demand on potable water supplies. Desalination plants, while essential, consume significant energy, so reducing water demand directly supports the UAE Energy Strategy 2050 goals.\n\nResidential customers can reduce water consumption by 30-50% by adopting simple measures: fixing leaks promptly, taking shorter showers, using efficient appliances, and watering gardens during cooler hours. MOEI provides free water audit services for large consumers and publishes conservation guidelines. The Waterwise initiative offers rebates for installing water-efficient devices. Schools and community organizations can request MOEI water conservation workshops and educational materials.",
    contentAr: "ترشيد استهلاك المياه هو أولوية حرجة لوزارة الطاقة والبنية التحتية نظراً للمناخ القاحل في الإمارة ومحدودية مصادر المياه العذبة الطبيعية. تُصنف الإمارات كواحدة من أعلى معدلات استهلاك المياه للفرد عالمياً، مما يجعل الترشيد ضرورة. تستهدف برامج استدامة المياه بالوزارة تخفيض استهلاك المياه السكني بنسبة 40% بحلول 2030 من خلال معايير الكفاءة وحملات التوعية ونشر التكنولوجيا الذكية.\n\nتُلزم الوزارة بتركيبات موفرة للمياه في جميع المباني الاتحادية الجديدة، بما في ذلك صنابير التدفق المنخفض ومراحيض الدفع المزدوج وتنسيق المناظر الطبيعية الموفرة للمياه. تشجع الوزارة إعادة استخدام مياه الصرف الصحي المعالجة للري والتبريد الصناعي، مما يقلل الطلب على إمدادات المياه الصالحة للشرب. محطات التحلية، رغم أهميتها، تستهلك طاقة كبيرة، لذا فإن تقليل الطلب على المياه يدعم مباشرة أهداف استراتيجية الطاقة الإماراتية 2050.\n\nيمكن للعملاء السكنيين تقليل استهلاك المياه بنسبة 30-50% بتبني إجراءات بسيطة: إصلاح التسريبات فوراً، أخذ حمامات أقصر، استخدام أجهزة موفرة، وري الحدائق خلال الساعات الأبرد. تقدم الوزارة خدمات تدقيق مياه مجانية للمستهلكين الكبار وتنشر إرشادات الترشيد. مبادرة Waterwise تقدم حوافز لتركيب أجهزة موفرة للمياه. يمكن للمدارس والمنظمات المجتمعية طلب ورش عمل ومواد تعليمية حول ترشيد المياه من الوزارة.",
    category: "Sustainability",
    tags: "water conservation, sustainability, desalination, efficiency, waterwise"
  },
  {
    id: "kb-sustain-005",
    titleEn: "Sustainable Transport and EV Infrastructure",
    titleAr: "النقل المستدام والبنية التحتية للمركبات الكهربائية",
    contentEn: "MOEI supports the transition to sustainable transport as part of the UAE's net-zero 2050 commitment. The ministry is developing regulatory frameworks for electric vehicle (EV) charging infrastructure on federal roads and at federal facilities. By 2030, the UAE aims for 10% of all vehicles on federal roads to be electric or hybrid, supported by a comprehensive charging network.\n\nEV charging station regulations include standards for installation safety, interoperability between charging networks, pricing transparency, and accessibility requirements. MOEI coordinates with the Ministry of Infrastructure Development and local transport authorities to ensure charging infrastructure covers all major routes. Federal buildings are required to allocate at least 5% of parking spaces for EV charging, with a target of 15% by 2030.\n\nFor transport operators, MOEI offers incentives for fleet electrification including priority licensing for electric commercial vehicles, reduced transport license fees, and technical assistance for charging infrastructure planning. The ministry also promotes sustainable freight practices including route optimization, load consolidation, and the use of alternative fuels. Pilot programs for hydrogen fuel cell vehicles are being evaluated for heavy transport applications on federal highways.",
    contentAr: "تدعم وزارة الطاقة والبنية التحتية التحول إلى النقل المستدام كجزء من التزام الإمارات بصافي انبعاثات صفرية بحلول 2050. تطور الوزارة أطراً تنظيمية للبنية التحتية لشحن المركبات الكهربائية على الطرق الاتحادية وفي المرافق الاتحادية. بحلول 2030، تستهدف الإمارات أن تشكل المركبات الكهربائية والهجينة 10% من جميع المركبات على الطرق الاتحادية، مدعومة بشبكة شحن شاملة.\n\nتشمل لوائح محطات شحن المركبات الكهربائية معايير سلامة التركيب والتشغيل البيني بين شبكات الشحن وشفافية الأسعار ومتطلبات إمكانية الوصول. تنسق الوزارة مع وزارة تطوير البنية التحتية وسلطات النقل المحلية لضمان تغطية البنية التحتية للشحن لجميع الطرق الرئيسية. يجب على المباني الاتحادية تخصيص 5% على الأقل من أماكن الوقوف لشحن المركبات الكهربائية، مع هدف 15% بحلول 2030.\n\nلمشغلي النقل، تقدم الوزارة حوافز لكهربة الأساطيل بما في ذلك الترخيص ذو الأولوية للمركبات التجارية الكهربائية ورسوم ترخيص نقل مخفضة ومساعدة فنية لتخطيط البنية التحتية للشحن. كما تشجع الوزارة ممارسات الشحن المستدامة بما في ذلك تحسين المسارات وتجميع الأحمال واستخدام الوقود البديل. يتم تقييم برامج تجريبية للمركبات بخلايا الوقود الهيدروجينية لتطبيقات النقل الثقيل على الطرق السريعة الاتحادية.",
    category: "Sustainability",
    tags: "sustainable transport, electric vehicle, EV charging, hydrogen, fleet, net zero"
  },

  // Additional articles to reach 30+
  {
    id: "kb-elect-009",
    titleEn: "Power Outage Reporting and Restoration",
    titleAr: "الإبلاغ عن انقطاع الكهرباء واستعادة الخدمة",
    contentEn: "Power outages can occur due to equipment failure, extreme weather, maintenance work, or overload during peak demand. If you experience a power outage, first check if it affects only your property (check your circuit breaker) or is a wider area outage. For area-wide outages, call the electricity emergency line 997 immediately. MOEI monitors the electrical grid 24/7 and typically dispatches crews within 30 minutes for unplanned outages.\n\nPlanned maintenance outages are announced at least 48 hours in advance via SMS, email, and the MOEI website. Customers registered with UAE PASS receive automatic notifications for planned outages in their area. Planned outages are typically scheduled during off-peak hours (midnight to 6 AM) to minimize disruption. If a planned outage will exceed 8 hours, MOEI provides temporary alternative power arrangements for affected residential customers.\n\nDuring outage restoration, MOEI prioritizes critical facilities (hospitals, water treatment plants, traffic systems), then residential areas, and finally commercial zones. Restoration time depends on the cause and extent of the outage. Customers can track outage status and estimated restoration times on the MOEI website or by calling 8005555. After restoration, customers should report any equipment damage that may have resulted from the outage for compensation assessment.",
    contentAr: "يمكن أن تحدث انقطاعات الكهرباء بسبب أعطال المعدات أو الطقس القاسي أو أعمال الصيانة أو الحمل الزائد خلال فترات الطلب الذروي. إذا تعرضت لانقطاع الكهرباء، تحقق أولاً مما إذا كان يؤثر فقط على عقارك (تحقق من قاطع الدائرة) أو انقطاع في منطقة أوسع. لانقطاعات المنطقة الواسعة، اتصل بخط طوارئ الكهرباء 997 فوراً. تراقب الوزارة الشبكة الكهربائية على مدار الساعة وعادة ما ترسل أطقم العمل خلال 30 دقيقة للانقطاعات غير المخططة.\n\nيتم الإعلان عن انقطاعات الصيانة المخططة قبل 48 ساعة على الأقل عبر الرسائل القصيرة والبريد الإلكتروني وموقع الوزارة. يتلقى العملاء المسجلون في UAE PASS إشعارات تلقائية للانقطاعات المخططة في منطقتهم. عادة ما تُجدول الانقطاعات المخططة خلال ساعات خارج الذروة (من منتصف الليل إلى 6 صباحاً) لتقليل الإزعاج. إذا تجاوز الانقطاع المخطط 8 ساعات، توفر الوزارة ترتيبات طاقة بديلة مؤقتة للعملاء السكنيين المتأثرين.\n\nأثناء استعادة الخدمة، تعطي الوزارة الأولوية للمرافق الحيوية (المستشفيات ومحطات معالجة المياه وأنظمة المرور)، ثم المناطق السكنية، وأخيراً المناطق التجارية. يعتمد وقت الاستعادة على سبب ونطاق الانقطاع. يمكن للعملاء متابعة حالة الانقطاع وأوقات الاستعادة المقدرة على موقع الوزارة أو بالاتصال على 8005555. بعد الاستعادة، يجب على العملاء الإبلاغ عن أي أضرار في المعدات قد تكون نتجت عن الانقطاع لتقييم التعويض.",
    category: "Electricity & Water",
    tags: "power outage, restoration, emergency, maintenance, 997, reporting"
  },
  {
    id: "kb-house-006",
    titleEn: "Housing for People of Determination",
    titleAr: "الإسكان لأصحاب الهمم",
    contentEn: "MOEI provides specialized housing support for UAE nationals who are people of determination (persons with disabilities). This includes priority access to housing grants, modified housing designs with accessibility features, and additional financial support for home modifications. The Sheikh Zayed Housing Program reserves a percentage of new housing units for people of determination with fully accessible designs.\n\nHome modification grants cover the cost of installing ramps, widening doorways, modifying bathrooms and kitchens, installing stair lifts or elevators, and adding smart home accessibility features. These grants do not require repayment and are available in addition to standard housing support. The maximum modification grant is AED 150,000 per property.\n\nPeople of determination receive priority processing for all housing applications, with reduced processing times of 15-30 days. MOEI service centers provide dedicated counters and accessibility features including sign language interpreters, Braille documents, and assistive technology. Housing advisors are trained to understand the specific needs of people of determination and provide tailored guidance throughout the application process.",
    contentAr: "توفر وزارة الطاقة والبنية التحتية دعماً سكنياً متخصصاً للمواطنين الإماراتيين من أصحاب الهمم (ذوي الإعاقة). يشمل ذلك الأولوية في الوصول إلى المنح السكنية والتصاميم السكنية المعدلة بميزات إمكانية الوصول والدعم المالي الإضافي لتعديلات المنازل. يحجز برنامج الشيخ زايد للإسكان نسبة من الوحدات السكنية الجديدة لأصحاب الهمم بتصاميم يسهل الوصول إليها بالكامل.\n\nتغطي منح تعديل المنازل تكلفة تركيب المنحدرات وتوسيع المداخل وتعديل الحمامات والمطابخ وتركيب مصاعد السلالم أو المصاعد وإضافة ميزات إمكانية الوصول للمنازل الذكية. هذه المنح لا تتطلب السداد وهي متاحة بالإضافة إلى دعم الإسكان القياسي. الحد الأقصى لمنحة التعديل هو 150,000 درهم لكل عقار.\n\nيتلقى أصحاب الهمم معالجة ذات أولوية لجميع طلبات الإسكان، مع أوقات معالجة مخفضة تتراوح من 15-30 يوماً. توفر مراكز خدمة الوزارة مكاتب مخصصة وميزات إمكانية الوصول بما في ذلك مترجمي لغة الإشارة ومستندات بطريقة برايل والتكنولوجيا المساعدة. المستشارون السكنيون مدربون على فهم الاحتياجات المحددة لأصحاب الهمم وتقديم إرشادات مخصصة طوال عملية التقديم.",
    category: "Housing",
    tags: "housing, people of determination, accessibility, disability, modification, grant"
  },
  {
    id: "kb-petrol-005",
    titleEn: "Natural Gas Distribution and Safety",
    titleAr: "توزيع الغاز الطبيعي والسلامة",
    contentEn: "MOEI regulates the safe distribution of natural gas for residential, commercial, and industrial use in the UAE. Natural gas distribution networks must comply with MOEI safety standards, including pipeline integrity management, leak detection systems, and emergency response protocols. All gas installations must be performed by MOEI-licensed technicians and inspected before commissioning.\n\nFor residential customers, natural gas is supplied through regulated distribution networks operated by licensed utilities. Gas meters are installed and maintained by the utility provider. If you smell gas (a distinctive odorant is added for safety), immediately evacuate the building, do not use electrical switches, and call the gas emergency number or 997 from outside the building. Never attempt to locate a gas leak yourself.\n\nIndustrial and commercial gas consumers must maintain gas safety records, conduct annual gas installation inspections, and ensure all gas appliances are properly maintained. MOEI conducts random safety inspections of gas installations and can issue compliance orders for any deficiencies. Gas safety awareness materials are available in Arabic and English on the MOEI website, covering topics such as gas appliance safety, carbon monoxide prevention, and emergency procedures.",
    contentAr: "تنظم وزارة الطاقة والبنية التحتية التوزيع الآمن للغاز الطبيعي للاستخدام السكني والتجاري والصناعي في الإمارات. يجب أن تتوافق شبكات توزيع الغاز الطبيعي مع معايير سلامة الوزارة، بما في ذلك إدارة سلامة خطوط الأنابيب وأنظمة كشف التسرب وبروتوكولات الاستجابة للطوارئ. يجب إجراء جميع تركيبات الغاز بواسطة فنيين مرخصين من الوزارة وفحصها قبل التشغيل.\n\nللعملاء السكنيين، يتم توفير الغاز الطبيعي من خلال شبكات توزيع منظمة تشغلها مرافق مرخصة. يتم تركيب وصيانة عدادات الغاز من قبل مقدم الخدمة. إذا شممت رائحة غاز (يُضاف عامل رائحة مميز للسلامة)، أخلي المبنى فوراً، لا تستخدم المفاتيح الكهربائية، واتصل برقم طوارئ الغاز أو 997 من خارج المبنى. لا تح أبداً البحث عن تسرب الغاز بنفسك.\n\nيجب على المستهلكين الصناعيين والتجاريين للغاز الحفاظ على سجلات سلامة الغاز وإجراء عمليات تفتيش سنوية لتركيبات الغاز وضمان صيانة جميع أجهزة الغاز بشكل صحيح. تجري الوزارة عمليات تفتيش سلامة عشوائية لتركيبات الغاز ويمكنها إصدار أوامر امتثال لأي أوجه قصور. مواد التوعية بسلامة الغاز متوفرة بالعربية والإنجليزية على موقع الوزارة، تغطي مواضيع مثل سلامة أجهزة الغاز والوقاية من أول أكسيد الكربون وإجراءات الطوارئ.",
    category: "Petroleum & Energy",
    tags: "natural gas, distribution, safety, pipeline, leak detection, emergency"
  },
  {
    id: "kb-general-006",
    titleEn: "MOEI Online Services Portal",
    titleAr: "بوابة الخدمات الإلكترونية لوزارة الطاقة والبنية التحتية",
    contentEn: "The MOEI online services portal at www.moei.gov.ae provides 24/7 access to government services without the need to visit a physical service center. The portal supports UAE PASS authentication for secure login and offers services across all MOEI categories: electricity and water, housing, petroleum, transport, and general services. The portal is available in both Arabic and English.\n\nKey online services include: applying for electricity and water connections, submitting and tracking housing loan applications, petroleum license renewals, transport license applications, bill payment and consumption monitoring, complaint submission and tracking, and downloading forms and guidelines. Most applications can be completed entirely online with digital document submission through UAE PASS.\n\nThe portal also provides access to MOEI's knowledge base, FAQ section, and service catalog. Real-time application status tracking is available for all submitted requests. The MOEI mobile app offers the same functionality with additional features such as push notifications for application updates and bill reminders. Technical support for the online portal is available by calling 8005555 during office hours.",
    contentAr: "توفر بوابة الخدمات الإلكترونية لوزارة الطاقة والبنية التحتية على www.moei.gov.ae وصولاً على مدار الساعة إلى الخدمات الحكومية دون الحاجة لزيارة مركز خدمة فعلي. تدعم البوابة مصادقة UAE PASS لتسجيل الدخول الآمن وتقدم خدمات عبر جميع فئات الوزارة: الكهرباء والمياه والإسكان والبترول والنقل والخدمات العامة. البوابة متوفرة باللغتين العربية والإنجليزية.\n\nتشمل الخدمات عبر الإنترنت الرئيسية: التقديم لتوصيلات الكهرباء والمياه، تقديم ومتابعة طلبات القروض الإسكانية، تجديد تراخيص البترول، طلبات ترخيص النقل، دفع الفواتير ومراقبة الاستهلاك، تقديم ومتابعة الشكاوى، وتحميل النماذج والإرشادات. يمكن إكمال معظم الطلبات بالكامل عبر الإنترنت مع تقديم المستندات الرقمية من خلال UAE PASS.\n\nتوفر البوابة أيضاً الوصول إلى قاعدة المعرفة بالوزارة وقسم الأسئلة الشائعة وكتالوج الخدمات. يتوفر تتبع حالة الطلب في الوقت الفعلي لجميع الطلبات المقدمة. يوفر تطبيق الوزارة المحمول نفس الوظائف مع ميزات إضافية مثل الإشعارات الفورية لتحديثات الطلبات وتذكيرات الفواتير. الدعم الفني للبوابة الإلكترونية متاح بالاتصال على 8005555 خلال ساعات العمل.",
    category: "General Services",
    tags: "online services, portal, website, digital, UAE PASS, mobile app"
  },
  {
    id: "kb-sustain-006",
    titleEn: "Waste Management and Circular Economy",
    titleAr: "إدارة النفايات والاقتصاد الدائري",
    contentEn: "MOEI supports waste management and circular economy initiatives as part of the UAE's sustainability agenda. The ministry regulates waste from energy and infrastructure operations, including construction and demolition waste, industrial waste from petroleum operations, and electronic waste from utility infrastructure. Federal construction projects must submit waste management plans demonstrating a minimum 75% waste diversion rate from landfills.\n\nThe circular economy framework encourages the reuse, recycling, and recovery of materials from infrastructure projects. MOEI promotes the use of recycled construction materials in federal projects, with standards for recycled aggregate, recycled concrete, and reclaimed building materials. The ministry also supports research into waste-to-energy technologies and has pilot programs for converting non-recyclable waste into energy.\n\nFor the petroleum sector, MOEI requires operators to implement waste minimization plans and report on waste generation and disposal. Produced water from oil operations must be treated and recycled where possible, with discharge standards strictly enforced. MOEI coordinates with the Environment Agency - Abu Dhabi and other environmental authorities to ensure consistent waste management standards across the UAE.",
    contentAr: "تدعم وزارة الطاقة والبنية التحتية مبادرات إدارة النفايات والاقتصاد الدائري كجزء من أجندة الاستدامة الإماراتية. تنظم الوزارة النفايات من عمليات الطاقة والبنية التحتية، بما في ذلك نفايات البناء والهدم والنفايات الصناعية من عمليات البترول والنفايات الإلكترونية من البنية التحتية للمرافق. يجب على مشاريع البناء الاتحادية تقديم خطط إدارة النفايات التي توضح معدل تحويل نفايات لا يقل عن 75% من المكبات.\n\nيشجع إطار الاقتصاد الدائري إعادة استخدام وتدوير واستعادة المواد من مشاريع البنية التحتية. تشجع الوزارة استخدام مواد البناء المعاد تدويرها في المشاريع الاتحادية، مع معايير للركام المعاد تدويره والخرسانة المعاد تدويرها ومواد البناء المسترجعة. كما تدعم الوزارة البحث في تقنيات تحويل النفايات إلى طاقة ولديها برامج تجريبية لتحويل النفايات غير القابلة للتدوير إلى طاقة.\n\nلقطاع البترول، تتطلب الوزارة من المشغلين تنفيذ خطط تقليل النفايات والإبلاغ عن توليد النفايات والتخلص منها. يجب معالجة مياه الإنتاج من عمليات النفط وإعادة تدويرها حيثما أمكن، مع تطبيق معايير التصريف بصرامة. تنسق الوزارة مع وكالة البيئة - أبوظبي والسلطات البيئية الأخرى لضمان معايير إدارة نفايات متسقة في جميع أنحاء الإمارات.",
    category: "Sustainability",
    tags: "waste management, circular economy, recycling, construction waste, sustainability"
  }
]

/**
 * Get all categories from the knowledge base
 */
export function getKnowledgeCategories(): string[] {
  const categories = new Set(moeiKnowledgeBase.map(a => a.category))
  return Array.from(categories)
}

/**
 * Search knowledge base by text query
 */
export function searchKnowledgeBase(query: string, limit = 5): KnowledgeArticle[] {
  const lowerQuery = query.toLowerCase()
  const scored = moeiKnowledgeBase.map(article => {
    let score = 0
    const searchFields = [
      article.titleEn.toLowerCase(),
      article.titleAr,
      article.contentEn.toLowerCase(),
      article.contentAr,
      article.category.toLowerCase(),
      article.tags.toLowerCase()
    ]
    for (const field of searchFields) {
      if (field.includes(lowerQuery)) score += 1
    }
    // Boost exact tag matches
    const queryWords = lowerQuery.split(/\s+/)
    const tagWords = article.tags.toLowerCase().split(',')
    for (const qw of queryWords) {
      for (const tw of tagWords) {
        if (tw.trim().includes(qw)) score += 2
      }
    }
    return { article, score }
  })

  return scored
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(s => s.article)
}

/**
 * Get articles by category
 */
export function getArticlesByCategory(category: string): KnowledgeArticle[] {
  return moeiKnowledgeBase.filter(a => a.category === category)
}

/**
 * Get article by ID
 */
export function getArticleById(id: string): KnowledgeArticle | undefined {
  return moeiKnowledgeBase.find(a => a.id === id)
}
