import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { data, filename } = body;

    const zip = new JSZip();

    // ── 1. Country Intelligence Report (JSON) ──
    const reportData = {
      metadata: {
        title: `MOEI Country Intelligence Report — ${data.country_name || data.country || 'Unknown'}`,
        iso3: data.country || data.iso3 || '',
        generated_at: data.generated_at || new Date().toISOString(),
        platform: 'MOEI Country Intelligence Platform v3.1.0',
        classification: 'CONFIDENTIAL — For Official Use Only',
      },
      executive_summary: data.read || null,
      analysis: data.analysis || null,
      insights: data.insights || [],
      risks: data.risks || [],
      opportunities: data.opportunities || [],
      headline: data.headline || [],
      trajectory: data.trajectory || [],
      trade: data.trade || null,
      sectors: data.sectors || [],
      energy: data.energy || [],
      uae_relations: data.uae || [],
      coverage: data.coverage || null,
      fields: data.fields || [],
      sources: data.sources || [],
    };

    zip.file('report.json', JSON.stringify(reportData, null, 2));

    // ── 2. Executive Summary (Markdown) ──
    let md = `# MOEI Country Intelligence Report\n\n`;
    md += `**Country:** ${data.country_name || data.country || 'Unknown'} (${data.country || data.iso3 || ''})  \n`;
    md += `**Generated:** ${new Date().toLocaleString()}  \n`;
    md += `**Classification:** CONFIDENTIAL — For Official Use Only  \n`;
    md += `**Platform:** MOEI Country Intelligence Platform v3.1.0\n\n`;
    md += `---\n\n`;

    if (data.read) {
      md += `## Executive Summary\n\n${data.read}\n\n---\n\n`;
    }

    if (data.analysis) {
      md += `## Analysis\n\n${data.analysis}\n\n---\n\n`;
    }

    if (data.insights && data.insights.length > 0) {
      md += `## Insights\n\n`;
      data.insights.forEach((panel: { title: string; content: string }, i: number) => {
        md += `### ${panel.title}\n\n${panel.content}\n\n`;
      });
      md += `---\n\n`;
    }

    if (data.opportunities && data.opportunities.length > 0) {
      md += `## Opportunities\n\n`;
      data.opportunities.forEach((panel: { title: string; content: string }, i: number) => {
        md += `### ${panel.title}\n\n${panel.content}\n\n`;
      });
      md += `---\n\n`;
    }

    if (data.risks && data.risks.length > 0) {
      md += `## Risks\n\n`;
      data.risks.forEach((panel: { title: string; content: string }, i: number) => {
        md += `### ${panel.title}\n\n${panel.content}\n\n`;
      });
      md += `---\n\n`;
    }

    if (data.headline && data.headline.length > 0) {
      md += `## Key Performance Indicators\n\n`;
      data.headline.forEach((h: { display: string; key: string; unit?: string }, i: number) => {
        md += `${i + 1}. **${h.display}**: ${h.key}${h.unit ? ` ${h.unit}` : ''}\n`;
      });
      md += `\n---\n\n`;
    }

    if (data.trade) {
      md += `## Trade Data\n\n`;
      md += `**Year:** ${data.trade.year}\n\n`;
      if (data.trade.export_partners) {
        md += `### Export Partners\n\n`;
        data.trade.export_partners.forEach((p: { name: string; share_pct: number }) => {
          md += `- ${p.name}: ${p.share_pct.toFixed(1)}%\n`;
        });
        md += '\n';
      }
      if (data.trade.import_partners) {
        md += `### Import Partners\n\n`;
        data.trade.import_partners.forEach((p: { name: string; share_pct: number }) => {
          md += `- ${p.name}: ${p.share_pct.toFixed(1)}%\n`;
        });
        md += '\n';
      }
      md += `---\n\n`;
    }

    if (data.uae && data.uae.length > 0) {
      md += `## UAE Relations\n\n`;
      data.uae.forEach((item: { display?: string; key: string; value: string | number; unit?: string }) => {
        md += `- **${item.display || item.key}**: ${item.value}${item.unit ? ` ${item.unit}` : ''}\n`;
      });
      md += '\n';
    }

    if (data.sources && data.sources.length > 0) {
      md += `## Sources\n\n`;
      data.sources.forEach((s: { label?: string; url: string; verified?: boolean }, i: number) => {
        md += `${i + 1}. [${s.label || s.url}](${s.url})${s.verified ? ' ✓' : ''}\n`;
      });
      md += '\n';
    }

    md += `\n---\n\n*Generated by MOEI Country Intelligence Platform v3.1.0*\n`;
    zip.file('report.md', md);

    // ── 3. KPI Summary (CSV) ──
    let csv = 'Metric,Value,Unit,Source\n';
    if (data.headline && data.headline.length > 0) {
      data.headline.forEach((h: { display: string; key: string; unit?: string; source?: string }) => {
        csv += `"${h.display}","${h.key}","${h.unit || ''}","${h.source || ''}"\n`;
      });
    }
    zip.file('kpi_summary.csv', csv);

    // ── 4. Trade Data (CSV) ──
    if (data.trade) {
      let tradeCsv = 'Type,Partner,Share (%)\n';
      if (data.trade.export_partners) {
        data.trade.export_partners.forEach((p: { name: string; share_pct: number }) => {
          tradeCsv += `Export,"${p.name}",${p.share_pct.toFixed(1)}\n`;
        });
      }
      if (data.trade.import_partners) {
        data.trade.import_partners.forEach((p: { name: string; share_pct: number }) => {
          tradeCsv += `Import,"${p.name}",${p.share_pct.toFixed(1)}\n`;
        });
      }
      zip.file('trade_data.csv', tradeCsv);
    }

    // ── 5. Fields Data (CSV) ──
    if (data.fields && data.fields.length > 0) {
      let fieldsCsv = 'Field,Domain,Value,Source,Confidence\n';
      data.fields.forEach((f: { field_name: string; domain?: string; value?: string; source_url?: string; confidence?: string }) => {
        fieldsCsv += `"${f.field_name}","${f.domain || ''}","${(f.value || '').replace(/"/g, '""')}","${f.source_url || ''}","${f.confidence || ''}"\n`;
      });
      zip.file('fields_data.csv', fieldsCsv);
    }

    // ── Generate ZIP ──
    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer' });

    const zipFilename = filename || `MOEI_Report_${data.country || 'export'}_${new Date().toISOString().slice(0, 10)}`;

    return new NextResponse(zipBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${zipFilename}.zip"`,
      },
    });
  } catch (error: unknown) {
    console.error('[ZIP export] Error:', error);
    return NextResponse.json(
      { error: 'Failed to generate ZIP file', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 },
    );
  }
}
